import {
  AlertOctagon,
  ArrowUpRight,
  Bot,
  CheckCircle2,
  Clipboard,
  Coins,
  Copy,
  FileCheck2,
  FileText,
  Filter,
  IndianRupee,
  Lightbulb,
  MapPin,
  Users,
  X,
} from "lucide-react";
import React, { useMemo, useState } from "react";

import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "../components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "../components/ui/dialog";
import { Progress } from "../components/ui/progress";
import { ScrollArea } from "../components/ui/scroll-area";
import { Separator } from "../components/ui/separator";

import type { PolicyGapInsight, SectorCategory } from "../types";
import { currencySymbol } from "../utils/country";

interface PlanGapMatrixProps {
  planGaps: PolicyGapInsight[];
  country?: string;
  onAskPolicyAi: (prompt: string) => void;
}

const sectorOptions: {
  id: SectorCategory | "ALL";
  label: string;
}[] = [
  { id: "ALL", label: "All sectors" },
  { id: "WATER_SUPPLY", label: "Water Supply" },
  { id: "RURAL_ROADS", label: "Rural Roads" },
  { id: "POWER_GRID", label: "Power Grid" },
  { id: "HEALTHCARE", label: "Healthcare" },
  { id: "SANITATION", label: "Sanitation" },
  { id: "FLOOD_DRAINAGE", label: "Flood & Drainage" },
];

const formatSector = (sector: string) =>
  sector
    .replace(/_/g, " ")
    .toLowerCase()
    .replace(/\b\w/g, (char) => char.toUpperCase());

export const PlanGapMatrix: React.FC<PlanGapMatrixProps> = ({
  planGaps,
  country,
  onAskPolicyAi,
}) => {
  const cur = currencySymbol(country);
  const [selectedSector, setSelectedSector] = useState<SectorCategory | "ALL">(
    "ALL",
  );

  const [activeMemo, setActiveMemo] = useState<PolicyGapInsight | null>(null);

  const [copied, setCopied] = useState(false);

  const filteredGaps = useMemo(() => {
    if (selectedSector === "ALL") return planGaps;

    return planGaps.filter((gap) => gap.sector === selectedSector);
  }, [planGaps, selectedSector]);

  const totalDeficit = useMemo(
    () =>
      filteredGaps.reduce(
        (sum, gap) => sum + gap.estimatedBudgetRequiredInCr,
        0,
      ),
    [filteredGaps],
  );

  const totalDemand = useMemo(
    () =>
      filteredGaps.length
        ? Math.round(
            filteredGaps.reduce((sum, gap) => sum + gap.citizenDemandScore, 0) /
              filteredGaps.length,
          )
        : 0,
    [filteredGaps],
  );

  const criticalGaps = useMemo(
    () =>
      filteredGaps.filter(
        (gap) => gap.citizenDemandScore >= 80 || gap.criticalComplaints > 0,
      ).length,
    [filteredGaps],
  );

  const noSchemeGaps = useMemo(
    () =>
      filteredGaps.filter((gap) => gap.activeProjectBudgetInCr === 0).length,
    [filteredGaps],
  );

  const handleCopyMemo = async () => {
    if (!activeMemo) return;

    const memoText = `NEXA POLICY ALLOCATION MEMO

SUBJECT:
Supplementary Budget Allocation for ${activeMemo.district} (${activeMemo.state})

COUNTRY:
${activeMemo.country}

SECTOR:
${formatSector(activeMemo.sector)}

RECOMMENDED ALLOCATION:
${cur}${activeMemo.estimatedBudgetRequiredInCr} Crore

CITIZEN DEMAND
Priority Score: ${activeMemo.citizenDemandScore}/100
Verified Citizen Requests: ${activeMemo.totalComplaints}
Critical Requests: ${activeMemo.criticalComplaints}
Affected Population: ${activeMemo.affectedPopulation.toLocaleString()}

CURRENT PLAN
Active Scheme Budget: ${cur}${activeMemo.activeProjectBudgetInCr} Cr
Active Schemes: ${activeMemo.activeProjectsCount}

INFRASTRUCTURE BOTTLENECK
${activeMemo.primaryKeyProblem}

AI EVIDENCE RATIONALE
${activeMemo.aiRationale}

RECOMMENDED ACTION
${activeMemo.recommendedAction}

Generated by Nexa BRICS Digital Public Infrastructure Intelligence Platform.`;

    try {
      await navigator.clipboard.writeText(memoText);
      setCopied(true);

      setTimeout(() => {
        setCopied(false);
      }, 2000);
    } catch {
      console.error("Unable to copy policy memo");
    }
  };

  const openAiAnalysis = () => {
    if (!activeMemo) return;

    const prompt = `Analyse the infrastructure gap in ${activeMemo.district}, ${activeMemo.state}, ${activeMemo.country}.

Sector: ${formatSector(activeMemo.sector)}

Citizen demand score: ${activeMemo.citizenDemandScore}/100
Total citizen requests: ${activeMemo.totalComplaints}
Critical requests: ${activeMemo.criticalComplaints}
Affected population: ${activeMemo.affectedPopulation}
Current scheme budget: ${cur}${activeMemo.activeProjectBudgetInCr} Cr
Estimated additional requirement: ${cur}${activeMemo.estimatedBudgetRequiredInCr} Cr

Primary infrastructure problem:
${activeMemo.primaryKeyProblem}

Existing evidence:
${activeMemo.aiRationale}

Recommended action:
${activeMemo.recommendedAction}

Provide:
1. Evidence-based interpretation of the gap
2. Suggested intervention
3. Implementation phases
4. Estimated resource requirements
5. Expected citizen impact
6. Key risks and dependencies
7. Metrics policymakers should monitor`;

    setActiveMemo(null);
    onAskPolicyAi(prompt);
  };

  return (
    <div className="space-y-6">
      {/* =========================================================
          PAGE HEADER
      ========================================================== */}
      <Card className="overflow-hidden border-slate-200 shadow-sm">
        <CardHeader className="border-b border-slate-200 bg-white p-5">
          <div className="flex flex-col gap-5 xl:flex-row xl:items-center xl:justify-between">
            {/* Title */}
            <div className="min-w-0">
              <div className="mb-2 flex flex-wrap items-center gap-2">
                <Badge
                  variant="secondary"
                  className="rounded-md bg-slate-100 text-slate-700"
                >
                  <FileCheck2 className="mr-1.5 h-3.5 w-3.5" />
                  Policy Gap Audit
                </Badge>

                <Badge
                  variant="outline"
                  className="rounded-md text-muted-foreground"
                >
                  FY 2025–26
                </Badge>

                <Badge
                  variant="outline"
                  className="rounded-md border-blue-200 bg-blue-50 text-blue-700"
                >
                  {filteredGaps.length} gaps identified
                </Badge>
              </div>

              <CardTitle className="text-xl font-semibold tracking-tight text-slate-950">
                Citizen Demand vs. Public Investment
              </CardTitle>

              <CardDescription className="mt-1.5 max-w-2xl text-sm leading-5">
                Compare citizen demand signals with existing government
                investment to identify infrastructure requirements that may need
                additional attention.
              </CardDescription>
            </div>

            {/* Unfunded Requirement KPI */}
            <div className="flex shrink-0 items-center gap-4 rounded-xl border border-rose-200 bg-rose-50/70 px-4 py-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-rose-100">
                <AlertOctagon className="h-4 w-4 text-rose-600" />
              </div>

              <div>
                <p className="text-[10px] font-semibold uppercase tracking-wider text-rose-700">
                  Estimated Unfunded Requirement
                </p>

                <div className="mt-0.5 flex items-baseline gap-1">
                  <span className="text-xl font-bold tracking-tight text-slate-950">
                    {cur}{totalDeficit.toLocaleString("en-US")}
                  </span>

                  <span className="text-xs font-medium text-slate-500">Cr</span>
                </div>
              </div>
            </div>
          </div>
        </CardHeader>

        {/* Filter / Action Toolbar */}
        <CardContent className="bg-slate-50/60 p-3.5">
          <div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between">
            {/* Sector Filters */}
            <div className="flex min-w-0 flex-wrap items-center gap-1.5">
              <div className="mr-1 flex items-center gap-1.5 text-xs font-semibold text-slate-600">
                <Filter className="h-3.5 w-3.5 text-slate-400" />
                Sector
              </div>

              <div className="flex flex-wrap gap-1.5">
                {sectorOptions.map((sector) => (
                  <Button
                    key={sector.id}
                    type="button"
                    size="sm"
                    variant={
                      selectedSector === sector.id ? "default" : "outline"
                    }
                    onClick={() => setSelectedSector(sector.id)}
                    className={
                      selectedSector === sector.id
                        ? "h-8 rounded-md bg-slate-900 px-3 text-xs text-white hover:bg-slate-800"
                        : "h-8 rounded-md border-slate-200 bg-white px-3 text-xs text-slate-600 hover:bg-slate-100 hover:text-slate-900"
                    }
                  >
                    {sector.label}
                  </Button>
                ))}
              </div>
            </div>

            {/* AI Action */}
            <Button
              size="sm"
              variant="outline"
              className="h-8 shrink-0 border-blue-200 bg-white text-blue-700 hover:bg-blue-50 hover:text-blue-800"
              onClick={() =>
                onAskPolicyAi(
                  "Analyse all current plan gaps. Identify the highest citizen-demand infrastructure gaps, explain the evidence behind them, and suggest policy interventions based on existing public investment.",
                )
              }
            >
              Ask Policy AI
              <ArrowUpRight className="ml-1.5 h-3.5 w-3.5" />
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* =========================================================
          SUMMARY STRIP
      ========================================================== */}
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-muted-foreground">
                Identified gaps
              </p>

              <FileText className="h-4 w-4 text-muted-foreground" />
            </div>

            <p className="mt-2 text-2xl font-bold tracking-tight">
              {filteredGaps.length}
            </p>

            <p className="mt-1 text-[11px] text-muted-foreground">
              Demand / plan mismatches
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-muted-foreground">
                Avg. demand score
              </p>

              <Users className="h-4 w-4 text-muted-foreground" />
            </div>

            <p className="mt-2 text-2xl font-bold tracking-tight">
              {totalDemand}
              <span className="ml-1 text-sm font-normal text-muted-foreground">
                /100
              </span>
            </p>

            <Progress value={totalDemand} className="mt-2 h-1.5" />
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-muted-foreground">
                Critical gaps
              </p>

              <AlertOctagon className="h-4 w-4 text-rose-600" />
            </div>

            <p className="mt-2 text-2xl font-bold text-rose-600">
              {criticalGaps}
            </p>

            <p className="mt-1 text-[11px] text-muted-foreground">
              High demand / urgent signals
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <p className="text-xs font-medium text-muted-foreground">
                No active scheme
              </p>

              <MapPin className="h-4 w-4 text-amber-600" />
            </div>

            <p className="mt-2 text-2xl font-bold text-amber-600">
              {noSchemeGaps}
            </p>

            <p className="mt-1 text-[11px] text-muted-foreground">
              No current investment detected
            </p>
          </CardContent>
        </Card>
      </div>

      {/* =========================================================
          EXPLANATION CARD
      ========================================================== */}
      <Card className="border-blue-100 bg-blue-50/40">
        <CardContent className="flex gap-3 p-4">
          <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-blue-100 text-blue-700">
            <Lightbulb className="h-4 w-4" />
          </div>

          <div>
            <p className="text-sm font-semibold text-slate-900">
              What this matrix tells policymakers
            </p>

            <p className="mt-1 text-xs leading-5 text-slate-600">
              A gap is surfaced when citizen demand signals are significant
              relative to the infrastructure currently funded in the same
              location and sector. Each row contains the evidence used to
              explain the mismatch.
            </p>
          </div>
        </CardContent>
      </Card>

      {/* =========================================================
          GAP TABLE
      ========================================================== */}
      <Card className="overflow-hidden">
        <CardHeader className="border-b bg-muted/30 px-4 py-4">
          <div className="flex items-center justify-between gap-4">
            <div>
              <CardTitle className="text-sm">
                Infrastructure Gap Register
              </CardTitle>

              <CardDescription className="mt-1 text-xs">
                {filteredGaps.length} records match the current filter
              </CardDescription>
            </div>

            <Badge variant="secondary">
              {selectedSector === "ALL"
                ? "All sectors"
                : formatSector(selectedSector)}
            </Badge>
          </div>
        </CardHeader>

        <CardContent className="p-0">
          {filteredGaps.length === 0 ? (
            <div className="flex min-h-[280px] flex-col items-center justify-center px-6 text-center">
              <div className="flex h-12 w-12 items-center justify-center rounded-full bg-muted">
                <CheckCircle2 className="h-6 w-6 text-emerald-600" />
              </div>

              <p className="mt-4 text-sm font-semibold">No gaps found</p>

              <p className="mt-1 max-w-sm text-xs text-muted-foreground">
                No policy gap records match the selected sector.
              </p>
            </div>
          ) : (
            <div className="overflow-x-auto">
              <table className="w-full min-w-[1050px] text-left">
                <thead className="border-b bg-muted/20">
                  <tr className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                    <th className="px-4 py-3">Location</th>
                    <th className="px-4 py-3">Sector</th>
                    <th className="px-4 py-3 text-center">Demand</th>
                    <th className="px-4 py-3 text-center">Current plan</th>
                    <th className="px-4 py-3">Infrastructure gap</th>
                    <th className="px-4 py-3 text-right">Requirement</th>
                    <th className="px-4 py-3 text-right">Action</th>
                  </tr>
                </thead>

                <tbody className="divide-y">
                  {filteredGaps.map((gap) => {
                    const demandColor =
                      gap.citizenDemandScore >= 80
                        ? "text-rose-600"
                        : gap.citizenDemandScore >= 60
                          ? "text-amber-600"
                          : "text-slate-900";

                    return (
                      <tr
                        key={gap.id}
                        className="group transition-colors hover:bg-muted/30"
                      >
                        {/* LOCATION */}
                        <td className="px-4 py-4 align-top">
                          <div className="flex items-start gap-2">
                            <div className="mt-0.5 flex h-7 w-7 shrink-0 items-center justify-center rounded-md bg-slate-100">
                              <MapPin className="h-3.5 w-3.5 text-slate-600" />
                            </div>

                            <div>
                              <p className="text-xs font-semibold text-slate-900">
                                {gap.district}
                              </p>

                              <p className="mt-0.5 text-[10px] text-muted-foreground">
                                {gap.state} · {gap.country}
                              </p>
                            </div>
                          </div>
                        </td>

                        {/* SECTOR */}
                        <td className="px-4 py-4 align-top">
                          <Badge
                            variant="secondary"
                            className="whitespace-nowrap text-[10px]"
                          >
                            {formatSector(gap.sector)}
                          </Badge>
                        </td>

                        {/* DEMAND */}
                        <td className="px-4 py-4 text-center align-top">
                          <div>
                            <span
                              className={`text-lg font-bold ${demandColor}`}
                            >
                              {gap.citizenDemandScore}
                            </span>

                            <span className="text-[10px] text-muted-foreground">
                              /100
                            </span>
                          </div>

                          <p className="mt-1 whitespace-nowrap text-[10px] text-muted-foreground">
                            {gap.totalComplaints} requests
                          </p>

                          {gap.criticalComplaints > 0 && (
                            <Badge
                              variant="outline"
                              className="mt-1 border-rose-200 bg-rose-50 text-[9px] text-rose-700"
                            >
                              {gap.criticalComplaints} critical
                            </Badge>
                          )}
                        </td>

                        {/* CURRENT PLAN */}
                        <td className="px-4 py-4 text-center align-top">
                          {gap.activeProjectBudgetInCr === 0 ? (
                            <Badge className="border-rose-200 bg-rose-50 text-[10px] text-rose-700 hover:bg-rose-50">
                              No active scheme
                            </Badge>
                          ) : (
                            <div>
                              <p className="whitespace-nowrap text-xs font-semibold">
                                {cur}
                                {gap.activeProjectBudgetInCr.toLocaleString(
                                  "en-US",
                                )}{" "}
                                Cr
                              </p>

                              <p className="mt-1 text-[10px] text-muted-foreground">
                                {gap.activeProjectsCount} active{" "}
                                {gap.activeProjectsCount === 1
                                  ? "scheme"
                                  : "schemes"}
                              </p>
                            </div>
                          )}
                        </td>

                        {/* PROBLEM */}
                        <td className="max-w-[280px] px-4 py-4 align-top">
                          <p className="line-clamp-2 text-xs font-medium leading-5 text-slate-900">
                            {gap.primaryKeyProblem}
                          </p>

                          <p className="mt-1 line-clamp-2 text-[10px] leading-4 text-muted-foreground">
                            {gap.aiRationale}
                          </p>
                        </td>

                        {/* REQUIREMENT */}
                        <td className="px-4 py-4 text-right align-top">
                          <p className="whitespace-nowrap text-sm font-bold text-rose-600">
                            {cur}
                            {gap.estimatedBudgetRequiredInCr.toLocaleString(
                              "en-US",
                            )}{" "}
                            Cr
                          </p>

                          <p className="mt-1 text-[10px] text-muted-foreground">
                            estimated requirement
                          </p>
                        </td>

                        {/* ACTION */}
                        <td className="px-4 py-4 text-right align-top">
                          <Button
                            size="sm"
                            className="h-8 whitespace-nowrap text-xs"
                            onClick={() => setActiveMemo(gap)}
                          >
                            <FileCheck2 className="mr-1.5 h-3.5 w-3.5" />
                            Review gap
                          </Button>
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
          )}
        </CardContent>
      </Card>

      {/* =========================================================
          POLICY MEMO DIALOG
      ========================================================== */}
      <Dialog
        open={!!activeMemo}
        onOpenChange={(open) => {
          if (!open) {
            setActiveMemo(null);
            setCopied(false);
          }
        }}
      >
        <DialogContent className="max-h-[90vh] w-[calc(100%-2rem)] max-w-3xl overflow-hidden p-0">
          {activeMemo && (
            <>
              <DialogHeader className="border-b bg-slate-950 px-6 py-5 text-white">
                <div className="flex items-start gap-3">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-white/10">
                    <FileCheck2 className="h-5 w-5 text-emerald-400" />
                  </div>

                  <div className="min-w-0">
                    <DialogTitle className="text-base text-white">
                      Policy Allocation Review
                    </DialogTitle>

                    <DialogDescription className="mt-1 text-xs text-slate-300">
                      Evidence-backed infrastructure gap for{" "}
                      <span className="font-medium text-white">
                        {activeMemo.district}
                      </span>
                      .
                    </DialogDescription>
                  </div>
                </div>
              </DialogHeader>

              <ScrollArea className="max-h-[calc(90vh-170px)]">
                <div className="space-y-6 p-6">
                  {/* Location / priority */}
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <div className="flex flex-wrap items-center gap-2">
                        <Badge variant="outline">{activeMemo.country}</Badge>

                        <Badge variant="secondary">
                          {formatSector(activeMemo.sector)}
                        </Badge>

                        {activeMemo.activeProjectBudgetInCr === 0 && (
                          <Badge className="border-rose-200 bg-rose-50 text-rose-700 hover:bg-rose-50">
                            No active scheme
                          </Badge>
                        )}
                      </div>

                      <h3 className="mt-2 text-lg font-bold tracking-tight">
                        {activeMemo.district}
                      </h3>

                      <p className="text-xs text-muted-foreground">
                        {activeMemo.state}
                      </p>
                    </div>

                    <div className="rounded-xl border bg-rose-50 px-4 py-3 text-right">
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-rose-700">
                        Estimated requirement
                      </p>

                      <p className="mt-1 text-xl font-bold text-rose-700">
                        {cur}
                        {activeMemo.estimatedBudgetRequiredInCr.toLocaleString(
                          "en-US",
                        )}{" "}
                        Cr
                      </p>
                    </div>
                  </div>

                  {/* Evidence cards */}
                  <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">
                    <Card className="shadow-none">
                      <CardContent className="p-3.5">
                        <Users className="h-4 w-4 text-muted-foreground" />

                        <p className="mt-2 text-lg font-bold">
                          {activeMemo.citizenDemandScore}
                        </p>

                        <p className="text-[10px] text-muted-foreground">
                          Demand score
                        </p>
                      </CardContent>
                    </Card>

                    <Card className="shadow-none">
                      <CardContent className="p-3.5">
                        <AlertOctagon className="h-4 w-4 text-rose-600" />

                        <p className="mt-2 text-lg font-bold">
                          {activeMemo.criticalComplaints}
                        </p>

                        <p className="text-[10px] text-muted-foreground">
                          Critical requests
                        </p>
                      </CardContent>
                    </Card>

                    <Card className="shadow-none">
                      <CardContent className="p-3.5">
                        <Coins className="h-4 w-4 text-muted-foreground" />

                        <p className="mt-2 text-lg font-bold">
                          {cur}{activeMemo.activeProjectBudgetInCr}
                        </p>

                        <p className="text-[10px] text-muted-foreground">
                          Current budget · Cr
                        </p>
                      </CardContent>
                    </Card>

                    <Card className="shadow-none">
                      <CardContent className="p-3.5">
                        <Users className="h-4 w-4 text-muted-foreground" />

                        <p className="mt-2 text-lg font-bold">
                          {activeMemo.affectedPopulation.toLocaleString(
                            "en-IN",
                          )}
                        </p>

                        <p className="text-[10px] text-muted-foreground">
                          Population affected
                        </p>
                      </CardContent>
                    </Card>
                  </div>

                  {/* Citizen demand */}
                  <section>
                    <div className="mb-2 flex items-center justify-between">
                      <div>
                        <h4 className="text-sm font-semibold">
                          Citizen demand signal
                        </h4>

                        <p className="text-[11px] text-muted-foreground">
                          {activeMemo.totalComplaints} verified requests
                          recorded
                        </p>
                      </div>

                      <span className="text-sm font-bold">
                        {activeMemo.citizenDemandScore}/100
                      </span>
                    </div>

                    <Progress
                      value={activeMemo.citizenDemandScore}
                      className="h-2"
                    />
                  </section>

                  <Separator />

                  {/* Problem */}
                  <section className="space-y-3">
                    <div>
                      <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                        Infrastructure bottleneck
                      </p>

                      <p className="mt-1 text-sm font-semibold text-slate-900">
                        {activeMemo.primaryKeyProblem}
                      </p>
                    </div>

                    <div className="rounded-xl border bg-muted/30 p-4">
                      <div className="flex gap-3">
                        <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-blue-100 text-blue-700">
                          <Bot className="h-4 w-4" />
                        </div>

                        <div>
                          <p className="text-xs font-semibold">
                            Evidence rationale
                          </p>

                          <p className="mt-1 text-xs leading-5 text-muted-foreground">
                            {activeMemo.aiRationale}
                          </p>
                        </div>
                      </div>
                    </div>
                  </section>

                  {/* Recommended action */}
                  <section>
                    <p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
                      Recommended policy action
                    </p>

                    <div className="mt-2 rounded-xl border border-emerald-200 bg-emerald-50/60 p-4">
                      <div className="flex gap-3">
                        <CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />

                        <p className="text-sm leading-6 text-slate-700">
                          {activeMemo.recommendedAction}
                        </p>
                      </div>
                    </div>
                  </section>

                  {/* Population impact */}
                  <section className="rounded-xl border bg-slate-50 p-4">
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-xs font-semibold">
                          Potential population impact
                        </p>

                        <p className="mt-1 text-[11px] text-muted-foreground">
                          Estimated residents affected by this gap
                        </p>
                      </div>

                      <p className="text-lg font-bold">
                        {activeMemo.affectedPopulation.toLocaleString("en-IN")}
                      </p>
                    </div>
                  </section>
                </div>
              </ScrollArea>

              <DialogFooter className="border-t bg-background px-6 py-4">
                <Button variant="outline" onClick={handleCopyMemo}>
                  {copied ? (
                    <CheckCircle2 className="mr-2 h-4 w-4 text-emerald-600" />
                  ) : (
                    <Copy className="mr-2 h-4 w-4" />
                  )}

                  {copied ? "Copied" : "Copy memo"}
                </Button>

                <Button onClick={openAiAnalysis}>
                  <Bot className="mr-2 h-4 w-4" />
                  Analyse with Policy AI
                  <ArrowUpRight className="ml-1.5 h-3.5 w-3.5" />
                </Button>
              </DialogFooter>
            </>
          )}
        </DialogContent>
      </Dialog>
    </div>
  );
};
