import {
  DistrictDemographic,
  GovernmentProject,
  Grievance,
  PolicyGapInsight,
} from '../types/index.js';

export const INITIAL_DISTRICTS: DistrictDemographic[] = [
  {
    id: 'dist_in_up_bahraich',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Bahraich',
    population: 3487000,
    ruralPercentage: 88.5,
    vulnerabilityIndex: 84,
    baselineWaterIndex: 32,
    baselineRoadIndex: 45,
    baselinePowerIndex: 51,
    baselineHealthIndex: 38,
    coordinates: { lat: 27.5706, lng: 81.5977 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 142.5,
  },
  {
    id: 'dist_in_up_gorakhpur',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Gorakhpur',
    population: 4440000,
    ruralPercentage: 81.2,
    vulnerabilityIndex: 62,
    baselineWaterIndex: 68,
    baselineRoadIndex: 72,
    baselinePowerIndex: 76,
    baselineHealthIndex: 65,
    coordinates: { lat: 26.7606, lng: 83.3732 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 5,
    sanctionedBudgetInCr: 410.0,
  },
  {
    id: 'dist_in_up_balrampur',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Balrampur',
    population: 2148000,
    ruralPercentage: 92.1,
    vulnerabilityIndex: 88,
    baselineWaterIndex: 28,
    baselineRoadIndex: 36,
    baselinePowerIndex: 42,
    baselineHealthIndex: 29,
    coordinates: { lat: 27.4300, lng: 82.1800 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 1,
    sanctionedBudgetInCr: 65.0,
  },
  {
    id: 'dist_in_up_shravasti',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Shravasti',
    population: 1117000,
    ruralPercentage: 96.5,
    vulnerabilityIndex: 91,
    baselineWaterIndex: 25,
    baselineRoadIndex: 31,
    baselinePowerIndex: 39,
    baselineHealthIndex: 24,
    coordinates: { lat: 27.7025, lng: 81.9360 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 1,
    sanctionedBudgetInCr: 48.0,
  },
  {
    id: 'dist_in_up_varanasi',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    population: 3676000,
    ruralPercentage: 56.6,
    vulnerabilityIndex: 41,
    baselineWaterIndex: 82,
    baselineRoadIndex: 86,
    baselinePowerIndex: 89,
    baselineHealthIndex: 84,
    coordinates: { lat: 25.3176, lng: 82.9739 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 8,
    sanctionedBudgetInCr: 920.0,
  },
  {
    id: 'dist_in_bihar_gaya',
    country: 'India',
    state: 'Bihar',
    district: 'Gaya',
    population: 4391000,
    ruralPercentage: 86.8,
    vulnerabilityIndex: 79,
    baselineWaterIndex: 39,
    baselineRoadIndex: 48,
    baselinePowerIndex: 58,
    baselineHealthIndex: 44,
    coordinates: { lat: 24.7914, lng: 85.0002 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 215.0,
  },
  {
    id: 'dist_in_bihar_muzaffarpur',
    country: 'India',
    state: 'Bihar',
    district: 'Muzaffarpur',
    population: 4801000,
    ruralPercentage: 90.4,
    vulnerabilityIndex: 73,
    baselineWaterIndex: 45,
    baselineRoadIndex: 52,
    baselinePowerIndex: 61,
    baselineHealthIndex: 49,
    coordinates: { lat: 26.1209, lng: 85.3647 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 188.0,
  },
  {
    id: 'dist_in_bihar_purnia',
    country: 'India',
    state: 'Bihar',
    district: 'Purnia',
    population: 3264000,
    ruralPercentage: 89.5,
    vulnerabilityIndex: 82,
    baselineWaterIndex: 35,
    baselineRoadIndex: 41,
    baselinePowerIndex: 47,
    baselineHealthIndex: 36,
    coordinates: { lat: 25.7771, lng: 87.4753 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 110.0,
  },
  {
    id: 'dist_in_mh_gadchiroli',
    country: 'India',
    state: 'Maharashtra',
    district: 'Gadchiroli',
    population: 1072000,
    ruralPercentage: 89.0,
    vulnerabilityIndex: 85,
    baselineWaterIndex: 41,
    baselineRoadIndex: 34,
    baselinePowerIndex: 46,
    baselineHealthIndex: 31,
    coordinates: { lat: 20.1809, lng: 80.0039 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 130.0,
  },
  {
    id: 'dist_in_mh_nandurbar',
    country: 'India',
    state: 'Maharashtra',
    district: 'Nandurbar',
    population: 1648000,
    ruralPercentage: 83.3,
    vulnerabilityIndex: 78,
    baselineWaterIndex: 44,
    baselineRoadIndex: 49,
    baselinePowerIndex: 54,
    baselineHealthIndex: 39,
    coordinates: { lat: 21.3700, lng: 74.2400 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 145.0,
  },
  {
    id: 'dist_in_mp_dhar',
    country: 'India',
    state: 'Madhya Pradesh',
    district: 'Dhar',
    population: 2185000,
    ruralPercentage: 81.1,
    vulnerabilityIndex: 71,
    baselineWaterIndex: 48,
    baselineRoadIndex: 56,
    baselinePowerIndex: 62,
    baselineHealthIndex: 47,
    coordinates: { lat: 22.5978, lng: 75.2974 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 175.0,
  },
  {
    id: 'dist_in_assam_sonitpur',
    country: 'India',
    state: 'Assam',
    district: 'Sonitpur',
    population: 1924000,
    ruralPercentage: 91.0,
    vulnerabilityIndex: 69,
    baselineWaterIndex: 49,
    baselineRoadIndex: 53,
    baselinePowerIndex: 57,
    baselineHealthIndex: 51,
    coordinates: { lat: 26.6528, lng: 92.7926 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 160.0,
  },
  {
    id: 'dist_in_tn_dharmapuri',
    country: 'India',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    population: 1506000,
    ruralPercentage: 82.7,
    vulnerabilityIndex: 53,
    baselineWaterIndex: 61,
    baselineRoadIndex: 78,
    baselinePowerIndex: 82,
    baselineHealthIndex: 74,
    coordinates: { lat: 12.1357, lng: 78.1584 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 4,
    sanctionedBudgetInCr: 280.0,
  },
  // BRICS Country Reference Profiles
  {
    id: 'dist_za_limpopo',
    country: 'South Africa',
    state: 'Limpopo',
    district: 'Vhembe',
    population: 1393000,
    ruralPercentage: 87.0,
    vulnerabilityIndex: 76,
    baselineWaterIndex: 38,
    baselineRoadIndex: 52,
    baselinePowerIndex: 64,
    baselineHealthIndex: 48,
    coordinates: { lat: -22.9576, lng: 30.4835 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 95.0,
  },
  {
    id: 'dist_br_amazonas',
    country: 'Brazil',
    state: 'Amazonas',
    district: 'Alto Solimões',
    population: 260000,
    ruralPercentage: 68.0,
    vulnerabilityIndex: 72,
    baselineWaterIndex: 42,
    baselineRoadIndex: 28,
    baselinePowerIndex: 51,
    baselineHealthIndex: 40,
    coordinates: { lat: -4.3644, lng: -69.9406 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 1,
    sanctionedBudgetInCr: 80.0,
  },
  // Russia districts (sample)
  {
    id: 'dist_rus_moskva',
    country: 'Russia',
    state: 'Moscow Oblast',
    district: 'Moscow',
    population: 12680000,
    ruralPercentage: 15.2,
    vulnerabilityIndex: 35,
    baselineWaterIndex: 85,
    baselineRoadIndex: 90,
    baselinePowerIndex: 92,
    baselineHealthIndex: 88,
    coordinates: { lat: 55.7558, lng: 37.6173 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 5,
    sanctionedBudgetInCr: 200.0,
  },
  {
    id: 'dist_rus_saint-petersburg',
    country: 'Russia',
    state: 'Leningrad Oblast',
    district: 'Saint Petersburg',
    population: 5399000,
    ruralPercentage: 12.5,
    vulnerabilityIndex: 42,
    baselineWaterIndex: 78,
    baselineRoadIndex: 82,
    baselinePowerIndex: 85,
    baselineHealthIndex: 79,
    coordinates: { lat: 59.9311, lng: 30.3609 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 120.0,
  },
  // China districts (sample)
  {
    id: 'dist_cn_beijing',
    country: 'China',
    state: 'Beijing',
    district: 'Beijing',
    population: 21540000,
    ruralPercentage: 21.3,
    vulnerabilityIndex: 48,
    baselineWaterIndex: 72,
    baselineRoadIndex: 85,
    baselinePowerIndex: 88,
    baselineHealthIndex: 82,
    coordinates: { lat: 39.9042, lng: 116.4074 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 8,
    sanctionedBudgetInCr: 500.0,
  },
  {
    id: 'dist_cn_shanghai',
    country: 'China',
    state: 'Shanghai',
    district: 'Shanghai',
    population: 24870000,
    ruralPercentage: 13.8,
    vulnerabilityIndex: 41,
    baselineWaterIndex: 88,
    baselineRoadIndex: 91,
    baselinePowerIndex: 90,
    baselineHealthIndex: 86,
    coordinates: { lat: 31.2304, lng: 121.4737 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 10,
    sanctionedBudgetInCr: 650.0,
  },
  // ---- Additional India coverage (map testing across states) ----
  {
    id: 'dist_in_rj_jaipur',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jaipur',
    population: 6626000,
    ruralPercentage: 52.4,
    vulnerabilityIndex: 58,
    baselineWaterIndex: 52,
    baselineRoadIndex: 74,
    baselinePowerIndex: 78,
    baselineHealthIndex: 66,
    coordinates: { lat: 26.9124, lng: 75.7873 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 4,
    sanctionedBudgetInCr: 310.0,
  },
  {
    id: 'dist_in_gj_ahmedabad',
    country: 'India',
    state: 'Gujarat',
    district: 'Ahmedabad',
    population: 7214000,
    ruralPercentage: 38.2,
    vulnerabilityIndex: 47,
    baselineWaterIndex: 71,
    baselineRoadIndex: 84,
    baselinePowerIndex: 88,
    baselineHealthIndex: 79,
    coordinates: { lat: 23.0225, lng: 72.5714 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 6,
    sanctionedBudgetInCr: 540.0,
  },
  {
    id: 'dist_in_ka_bengaluru',
    country: 'India',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    population: 9621000,
    ruralPercentage: 18.5,
    vulnerabilityIndex: 44,
    baselineWaterIndex: 58,
    baselineRoadIndex: 81,
    baselinePowerIndex: 86,
    baselineHealthIndex: 82,
    coordinates: { lat: 12.9716, lng: 77.5946 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 7,
    sanctionedBudgetInCr: 610.0,
  },
  {
    id: 'dist_in_kl_wayanad',
    country: 'India',
    state: 'Kerala',
    district: 'Wayanad',
    population: 817000,
    ruralPercentage: 93.1,
    vulnerabilityIndex: 66,
    baselineWaterIndex: 63,
    baselineRoadIndex: 59,
    baselinePowerIndex: 74,
    baselineHealthIndex: 71,
    coordinates: { lat: 11.685, lng: 76.132 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 120.0,
  },
  {
    id: 'dist_in_pb_ludhiana',
    country: 'India',
    state: 'Punjab',
    district: 'Ludhiana',
    population: 3498000,
    ruralPercentage: 42.8,
    vulnerabilityIndex: 49,
    baselineWaterIndex: 66,
    baselineRoadIndex: 83,
    baselinePowerIndex: 87,
    baselineHealthIndex: 78,
    coordinates: { lat: 30.901, lng: 75.8573 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 4,
    sanctionedBudgetInCr: 295.0,
  },
  {
    id: 'dist_in_wb_murshidabad',
    country: 'India',
    state: 'West Bengal',
    district: 'Murshidabad',
    population: 7108000,
    ruralPercentage: 87.6,
    vulnerabilityIndex: 74,
    baselineWaterIndex: 47,
    baselineRoadIndex: 55,
    baselinePowerIndex: 60,
    baselineHealthIndex: 52,
    coordinates: { lat: 24.18, lng: 88.27 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 190.0,
  },
  {
    id: 'dist_in_od_kalahandi',
    country: 'India',
    state: 'Odisha',
    district: 'Kalahandi',
    population: 1578000,
    ruralPercentage: 94.2,
    vulnerabilityIndex: 83,
    baselineWaterIndex: 36,
    baselineRoadIndex: 42,
    baselinePowerIndex: 50,
    baselineHealthIndex: 40,
    coordinates: { lat: 20.08, lng: 83.2 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 135.0,
  },
  {
    id: 'dist_in_up_lucknow',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Lucknow',
    population: 4589000,
    ruralPercentage: 41.5,
    vulnerabilityIndex: 46,
    baselineWaterIndex: 74,
    baselineRoadIndex: 85,
    baselinePowerIndex: 89,
    baselineHealthIndex: 80,
    coordinates: { lat: 26.8467, lng: 80.9462 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 6,
    sanctionedBudgetInCr: 480.0,
  },
  // ---- Egypt ----
  {
    id: 'dist_eg_giza',
    country: 'Egypt',
    state: 'Giza',
    district: 'Giza',
    population: 8800000,
    ruralPercentage: 42.0,
    vulnerabilityIndex: 64,
    baselineWaterIndex: 55,
    baselineRoadIndex: 62,
    baselinePowerIndex: 70,
    baselineHealthIndex: 58,
    coordinates: { lat: 29.987, lng: 31.21 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 210.0,
  },
  {
    id: 'dist_eg_aswan',
    country: 'Egypt',
    state: 'Aswan',
    district: 'Aswan',
    population: 1490000,
    ruralPercentage: 78.0,
    vulnerabilityIndex: 71,
    baselineWaterIndex: 48,
    baselineRoadIndex: 51,
    baselinePowerIndex: 63,
    baselineHealthIndex: 54,
    coordinates: { lat: 24.0889, lng: 32.8998 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 110.0,
  },
  // ---- Ethiopia ----
  {
    id: 'dist_et_addis',
    country: 'Ethiopia',
    state: 'Addis Ababa',
    district: 'Addis Ababa',
    population: 5200000,
    ruralPercentage: 12.0,
    vulnerabilityIndex: 59,
    baselineWaterIndex: 51,
    baselineRoadIndex: 60,
    baselinePowerIndex: 65,
    baselineHealthIndex: 57,
    coordinates: { lat: 9.03, lng: 38.74 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 150.0,
  },
  {
    id: 'dist_et_gondar',
    country: 'Ethiopia',
    state: 'Amhara',
    district: 'Gondar',
    population: 3500000,
    ruralPercentage: 86.0,
    vulnerabilityIndex: 81,
    baselineWaterIndex: 33,
    baselineRoadIndex: 38,
    baselinePowerIndex: 44,
    baselineHealthIndex: 36,
    coordinates: { lat: 12.6, lng: 37.47 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 1,
    sanctionedBudgetInCr: 60.0,
  },
  // ---- Iran ----
  {
    id: 'dist_ir_tehran',
    country: 'Iran',
    state: 'Tehran',
    district: 'Tehran',
    population: 13500000,
    ruralPercentage: 18.0,
    vulnerabilityIndex: 45,
    baselineWaterIndex: 60,
    baselineRoadIndex: 78,
    baselinePowerIndex: 82,
    baselineHealthIndex: 75,
    coordinates: { lat: 35.6892, lng: 51.389 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 5,
    sanctionedBudgetInCr: 320.0,
  },
  {
    id: 'dist_ir_ahvaz',
    country: 'Iran',
    state: 'Khuzestan',
    district: 'Ahvaz',
    population: 1300000,
    ruralPercentage: 55.0,
    vulnerabilityIndex: 70,
    baselineWaterIndex: 42,
    baselineRoadIndex: 56,
    baselinePowerIndex: 61,
    baselineHealthIndex: 52,
    coordinates: { lat: 31.32, lng: 48.67 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 130.0,
  },
  // ---- Saudi Arabia ----
  {
    id: 'dist_sa_riyadh',
    country: 'Saudi Arabia',
    state: 'Riyadh',
    district: 'Riyadh',
    population: 7500000,
    ruralPercentage: 15.0,
    vulnerabilityIndex: 38,
    baselineWaterIndex: 58,
    baselineRoadIndex: 86,
    baselinePowerIndex: 91,
    baselineHealthIndex: 84,
    coordinates: { lat: 24.7136, lng: 46.6753 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 6,
    sanctionedBudgetInCr: 420.0,
  },
  {
    id: 'dist_sa_jeddah',
    country: 'Saudi Arabia',
    state: 'Makkah',
    district: 'Jeddah',
    population: 4300000,
    ruralPercentage: 12.0,
    vulnerabilityIndex: 42,
    baselineWaterIndex: 62,
    baselineRoadIndex: 84,
    baselinePowerIndex: 89,
    baselineHealthIndex: 82,
    coordinates: { lat: 21.4858, lng: 39.1925 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 4,
    sanctionedBudgetInCr: 300.0,
  },
  // ---- UAE ----
  {
    id: 'dist_ae_dubai',
    country: 'UAE',
    state: 'Dubai',
    district: 'Dubai',
    population: 3400000,
    ruralPercentage: 5.0,
    vulnerabilityIndex: 30,
    baselineWaterIndex: 80,
    baselineRoadIndex: 92,
    baselinePowerIndex: 94,
    baselineHealthIndex: 90,
    coordinates: { lat: 25.2048, lng: 55.2708 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 5,
    sanctionedBudgetInCr: 380.0,
  },
  {
    id: 'dist_ae_abudhabi',
    country: 'UAE',
    state: 'Abu Dhabi',
    district: 'Abu Dhabi',
    population: 2800000,
    ruralPercentage: 18.0,
    vulnerabilityIndex: 33,
    baselineWaterIndex: 76,
    baselineRoadIndex: 90,
    baselinePowerIndex: 93,
    baselineHealthIndex: 88,
    coordinates: { lat: 24.4539, lng: 54.3773 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 4,
    sanctionedBudgetInCr: 340.0,
  },
  // ---- Indonesia ----
  {
    id: 'dist_id_jakarta',
    country: 'Indonesia',
    state: 'Jakarta',
    district: 'East Jakarta',
    population: 2900000,
    ruralPercentage: 8.0,
    vulnerabilityIndex: 55,
    baselineWaterIndex: 59,
    baselineRoadIndex: 72,
    baselinePowerIndex: 80,
    baselineHealthIndex: 70,
    coordinates: { lat: -6.2, lng: 106.85 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 4,
    sanctionedBudgetInCr: 260.0,
  },
  {
    id: 'dist_id_surabaya',
    country: 'Indonesia',
    state: 'East Java',
    district: 'Surabaya',
    population: 2900000,
    ruralPercentage: 22.0,
    vulnerabilityIndex: 57,
    baselineWaterIndex: 57,
    baselineRoadIndex: 70,
    baselinePowerIndex: 78,
    baselineHealthIndex: 68,
    coordinates: { lat: -7.25, lng: 112.75 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 220.0,
  },
  // ---- Extra BRICS depth (map density) ----
  {
    id: 'dist_za_ortambo',
    country: 'South Africa',
    state: 'Eastern Cape',
    district: 'OR Tambo',
    population: 1900000,
    ruralPercentage: 91.0,
    vulnerabilityIndex: 79,
    baselineWaterIndex: 40,
    baselineRoadIndex: 45,
    baselinePowerIndex: 55,
    baselineHealthIndex: 43,
    coordinates: { lat: -31.0, lng: 29.0 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 2,
    sanctionedBudgetInCr: 105.0,
  },
  {
    id: 'dist_br_para',
    country: 'Brazil',
    state: 'Para',
    district: 'Santarem',
    population: 310000,
    ruralPercentage: 62.0,
    vulnerabilityIndex: 68,
    baselineWaterIndex: 46,
    baselineRoadIndex: 35,
    baselinePowerIndex: 58,
    baselineHealthIndex: 50,
    coordinates: { lat: -2.44, lng: -54.7 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 1,
    sanctionedBudgetInCr: 70.0,
  },
  {
    id: 'dist_ru_novosibirsk',
    country: 'Russia',
    state: 'Novosibirsk Oblast',
    district: 'Novosibirsk',
    population: 2800000,
    ruralPercentage: 28.0,
    vulnerabilityIndex: 50,
    baselineWaterIndex: 70,
    baselineRoadIndex: 75,
    baselinePowerIndex: 80,
    baselineHealthIndex: 72,
    coordinates: { lat: 55.03, lng: 82.92 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 3,
    sanctionedBudgetInCr: 150.0,
  },
  {
    id: 'dist_cn_guangzhou',
    country: 'China',
    state: 'Guangdong',
    district: 'Guangzhou',
    population: 18600000,
    ruralPercentage: 25.0,
    vulnerabilityIndex: 46,
    baselineWaterIndex: 75,
    baselineRoadIndex: 87,
    baselinePowerIndex: 89,
    baselineHealthIndex: 83,
    coordinates: { lat: 23.1291, lng: 113.2644 },
    totalComplaintsCount: 0,
    unresolvedCount: 0,
    criticalComplaintsCount: 0,
    activeProjectsCount: 7,
    sanctionedBudgetInCr: 480.0,
  },
];

export const INITIAL_PROJECTS: GovernmentProject[] = [
  {
    id: 'proj_01',
    projectCode: 'JJM-UP-BAH-2024-08',
    title: 'Rural Piped Water Supply Network - Phakharpur & Kaisarganj',
    schemeName: 'Jal Jeevan Mission (JJM)',
    sector: 'WATER_SUPPLY',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Bahraich',
    sanctionedBudgetInCr: 68.5,
    spentBudgetInCr: 21.2,
    targetBeneficiaries: 185000,
    status: 'IN_PROGRESS',
    startDate: '2024-03-15',
    expectedCompletionDate: '2026-11-30',
    description: 'Installation of overhead tanks, 140km pipeline and household tap connections across 42 revenue villages.',
    implementingAgency: 'UP Jal Nigam (Rural)',
    impactMetricBefore: { metricName: 'Tap Water Coverage %', value: 24.5, unit: '%' },
    impactMetricAfter: { metricName: 'Target Coverage %', value: 85.0, unit: '%' },
  },
  {
    id: 'proj_02',
    projectCode: 'PMGSY-UP-BAH-2025-14',
    title: 'All-Weather Link Road Connecting Mahsi Block to District Highway',
    schemeName: 'Pradhan Mantri Gram Sadak Yojana (PMGSY-III)',
    sector: 'RURAL_ROADS',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Bahraich',
    sanctionedBudgetInCr: 74.0,
    spentBudgetInCr: 58.0,
    targetBeneficiaries: 95000,
    status: 'IN_PROGRESS',
    startDate: '2024-01-10',
    expectedCompletionDate: '2026-08-30',
    description: 'Construction of 38 km blacktop paved road with 4 culverts to prevent annual flood isolation.',
    implementingAgency: 'UP PWD Rural Division',
  },
  {
    id: 'proj_03',
    projectCode: 'FLDRAIN-UP-GKP-2023-01',
    title: 'Gorakhpur Urban & Peri-Urban Stormwater Drainage & Desilting Project',
    schemeName: 'AMRUT 2.0 Flood Mitigation Plan',
    sector: 'FLOOD_DRAINAGE',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Gorakhpur',
    sanctionedBudgetInCr: 145.0,
    spentBudgetInCr: 142.5,
    targetBeneficiaries: 620000,
    status: 'COMPLETED',
    startDate: '2023-02-01',
    expectedCompletionDate: '2025-06-30',
    actualCompletionDate: '2025-05-20',
    description: 'Construction of 52 km primary concrete storm drains and 3 automated pump stations at Ramgarh Tal outfall.',
    implementingAgency: 'Gorakhpur Smart City Corp',
    impactMetricBefore: { metricName: 'Monsoon Waterlogging Days / Year', value: 24, unit: 'days' },
    impactMetricAfter: { metricName: 'Monsoon Waterlogging Days / Year', value: 3, unit: 'days' },
  },
  {
    id: 'proj_04',
    projectCode: 'RDSS-UP-VAR-2024-09',
    title: 'Smart Metering & Underground Cabling System Phase 2',
    schemeName: 'Revamped Distribution Sector Scheme (RDSS)',
    sector: 'POWER_GRID',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    sanctionedBudgetInCr: 320.0,
    spentBudgetInCr: 290.0,
    targetBeneficiaries: 1200000,
    status: 'COMPLETED',
    startDate: '2023-10-01',
    expectedCompletionDate: '2025-09-30',
    actualCompletionDate: '2025-08-15',
    description: 'Substation modernization, 24x7 smart grid feed, and replacement of 180km aerial bunched cable.',
    implementingAgency: 'Purvanchal Vidyut Vitaran Nigam Ltd',
    impactMetricBefore: { metricName: 'Average Daily Outage Hours', value: 8.4, unit: 'hrs/day' },
    impactMetricAfter: { metricName: 'Average Daily Outage Hours', value: 0.9, unit: 'hrs/day' },
  },
  {
    id: 'proj_05',
    projectCode: 'JJM-BR-GAYA-2024-03',
    title: 'Gaya Southern Plateau Deep Borewell & Fluoride Treatment Plant',
    schemeName: 'Jal Jeevan Mission (JJM)',
    sector: 'WATER_SUPPLY',
    country: 'India',
    state: 'Bihar',
    district: 'Gaya',
    sanctionedBudgetInCr: 88.0,
    spentBudgetInCr: 34.0,
    targetBeneficiaries: 220000,
    status: 'IN_PROGRESS',
    startDate: '2024-06-01',
    expectedCompletionDate: '2027-01-31',
    description: 'Community water purification units and 65 solar powered mini-piped supply schemes for fluoride hit villages.',
    implementingAgency: 'Bihar PHED',
  },
  {
    id: 'proj_06',
    projectCode: 'PMABHIM-BR-MUZ-2024-07',
    title: 'Establishment of 14 Block Public Health Units & Critical Care Beds',
    schemeName: 'PM Ayushman Bharat Health Infrastructure Mission (PM-ABHIM)',
    sector: 'HEALTHCARE',
    country: 'India',
    state: 'Bihar',
    district: 'Muzaffarpur',
    sanctionedBudgetInCr: 94.0,
    spentBudgetInCr: 41.5,
    targetBeneficiaries: 450000,
    status: 'IN_PROGRESS',
    startDate: '2024-04-10',
    expectedCompletionDate: '2026-10-15',
    description: 'Creation of modern diagnostic labs and emergency beds across Kanti, Minapur and Motipur community health centers.',
    implementingAgency: 'Bihar State Health Society',
  },
  {
    id: 'proj_07',
    projectCode: 'PMGSY-MH-GAD-2024-12',
    title: 'Aheri-Etapalli Remote Forest Corridor Connectivity Road',
    schemeName: 'Pradhan Mantri Gram Sadak Yojana (PMGSY)',
    sector: 'RURAL_ROADS',
    country: 'India',
    state: 'Maharashtra',
    district: 'Gadchiroli',
    sanctionedBudgetInCr: 82.0,
    spentBudgetInCr: 28.0,
    targetBeneficiaries: 48000,
    status: 'IN_PROGRESS',
    startDate: '2024-08-01',
    expectedCompletionDate: '2027-03-31',
    description: 'Bridge construction over Dina river tributary and 44km asphalt road for isolated tribal settlements.',
    implementingAgency: 'Maharashtra Rural Road Dev Agency',
  },
  {
    id: 'proj_08',
    projectCode: 'SBM-TN-DHA-2024-02',
    title: 'Integrated Solid & Liquid Waste Treatment Plant Cluster',
    schemeName: 'Swachh Bharat Mission (Grameen) Phase 2',
    sector: 'SANITATION',
    country: 'India',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    sanctionedBudgetInCr: 72.0,
    spentBudgetInCr: 68.0,
    targetBeneficiaries: 310000,
    status: 'COMPLETED',
    startDate: '2023-11-01',
    expectedCompletionDate: '2025-04-30',
    actualCompletionDate: '2025-04-12',
    description: 'Greywater treatment units and 32 decentralized bio-methanation facilities in panchayat clusters.',
    implementingAgency: 'Tamil Nadu Rural Dev Dept',
    impactMetricBefore: { metricName: 'Open Drainage Overflow Grievances / Mo', value: 165, unit: 'complaints' },
    impactMetricAfter: { metricName: 'Open Drainage Overflow Grievances / Mo', value: 14, unit: 'complaints' },
  },
  {
    id: 'proj_09',
    projectCode: 'JJM-RJ-JAI-2024-05',
    title: 'Sanganer Zone Booster Pumping & Pipeline Replacement',
    schemeName: 'Jal Jeevan Mission (Urban)',
    sector: 'WATER_SUPPLY',
    country: 'India',
    state: 'Rajasthan',
    district: 'Jaipur',
    sanctionedBudgetInCr: 56.0,
    spentBudgetInCr: 18.5,
    targetBeneficiaries: 220000,
    status: 'IN_PROGRESS',
    startDate: '2024-05-01',
    expectedCompletionDate: '2026-12-31',
    description: 'Booster stations and 28km replacement of leaking CI pipelines in Sanganer.',
    implementingAgency: 'PHED Rajasthan',
  },
  {
    id: 'proj_10',
    projectCode: 'AMRUT-KA-BLR-2024-11',
    title: 'Bellandur Storm Drain Remediation & Lake Inlet Desilting',
    schemeName: 'AMRUT 2.0',
    sector: 'FLOOD_DRAINAGE',
    country: 'India',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    sanctionedBudgetInCr: 95.0,
    spentBudgetInCr: 40.0,
    targetBeneficiaries: 480000,
    status: 'IN_PROGRESS',
    startDate: '2024-07-01',
    expectedCompletionDate: '2026-09-30',
    description: 'Secondary drain widening and encroachment removal around Bellandur inlet.',
    implementingAgency: 'BBMP Stormwater Division',
  },
  {
    id: 'proj_11',
    projectCode: 'PMJANMAN-OD-KAL-2024-04',
    title: 'Kalahandi PVTG Hamlet Health & Water Access Package',
    schemeName: 'PM-JANMAN',
    sector: 'HEALTHCARE',
    country: 'India',
    state: 'Odisha',
    district: 'Kalahandi',
    sanctionedBudgetInCr: 48.0,
    spentBudgetInCr: 12.0,
    targetBeneficiaries: 90000,
    status: 'IN_PROGRESS',
    startDate: '2024-06-15',
    expectedCompletionDate: '2027-02-28',
    description: 'Mobile medical units and solar borewells for remote tribal hamlets.',
    implementingAgency: 'Odisha Tribal Dept',
  },
  {
    id: 'proj_12',
    projectCode: 'EG-GIZA-WS-2024-01',
    title: 'Faisal District Asbestos Pipe Replacement Program',
    schemeName: 'Egypt National Water Renewal',
    sector: 'WATER_SUPPLY',
    country: 'Egypt',
    state: 'Giza',
    district: 'Giza',
    sanctionedBudgetInCr: 62.0,
    spentBudgetInCr: 20.0,
    targetBeneficiaries: 350000,
    status: 'IN_PROGRESS',
    startDate: '2024-04-01',
    expectedCompletionDate: '2026-10-31',
    description: 'Replace 45km asbestos cement pipes with HDPE trunk mains.',
    implementingAgency: 'Giza Water Company',
  },
  {
    id: 'proj_13',
    projectCode: 'ET-AMH-HL-2024-02',
    title: 'Gondar Rural Health Post Drug Supply & Solar Cold Chain',
    schemeName: 'Ethiopia Health Extension Program',
    sector: 'HEALTHCARE',
    country: 'Ethiopia',
    state: 'Amhara',
    district: 'Gondar',
    sanctionedBudgetInCr: 28.0,
    spentBudgetInCr: 8.0,
    targetBeneficiaries: 180000,
    status: 'IN_PROGRESS',
    startDate: '2024-08-01',
    expectedCompletionDate: '2026-11-30',
    description: 'Solar fridges and essential drug revolving fund for 22 health posts.',
    implementingAgency: 'Amhara Health Bureau',
  },
  {
    id: 'proj_14',
    projectCode: 'SA-RYD-PW-2024-03',
    title: 'Al Naseem Feeder Reinforcement & Substation Upgrade',
    schemeName: 'Saudi Grid Resilience Plan',
    sector: 'POWER_GRID',
    country: 'Saudi Arabia',
    state: 'Riyadh',
    district: 'Riyadh',
    sanctionedBudgetInCr: 88.0,
    spentBudgetInCr: 55.0,
    targetBeneficiaries: 500000,
    status: 'IN_PROGRESS',
    startDate: '2024-03-01',
    expectedCompletionDate: '2025-12-31',
    description: 'Additional 132/33kV capacity and smart feeder automation.',
    implementingAgency: 'Saudi Electricity Co.',
  },
  {
    id: 'proj_15',
    projectCode: 'ID-JKT-DR-2024-06',
    title: 'Cakung Secondary Drain Dredging & Waste Trap Installation',
    schemeName: 'Jakarta Flood Mitigation Program',
    sector: 'FLOOD_DRAINAGE',
    country: 'Indonesia',
    state: 'Jakarta',
    district: 'East Jakarta',
    sanctionedBudgetInCr: 44.0,
    spentBudgetInCr: 15.0,
    targetBeneficiaries: 260000,
    status: 'IN_PROGRESS',
    startDate: '2024-09-01',
    expectedCompletionDate: '2026-08-31',
    description: 'Dredging, trash racks and community waste collection points.',
    implementingAgency: 'DKI Water Agency',
  },
  {
    id: 'proj_16',
    projectCode: 'BR-PA-WS-2024-02',
    title: 'Santarem Mini Treatment Plant Pump Refurbishment',
    schemeName: 'Para Safe Water Program',
    sector: 'WATER_SUPPLY',
    country: 'Brazil',
    state: 'Para',
    district: 'Santarem',
    sanctionedBudgetInCr: 22.0,
    spentBudgetInCr: 6.0,
    targetBeneficiaries: 60000,
    status: 'IN_PROGRESS',
    startDate: '2024-10-01',
    expectedCompletionDate: '2026-06-30',
    description: 'Pump replacement and riverbank intake protection.',
    implementingAgency: 'COSANPA Para',
  },
  {
    id: 'proj_17',
    projectCode: 'ZA-EC-PW-2024-01',
    title: 'Lusikisiki Clinic Feeder Stabilization',
    schemeName: 'Eastern Cape Energy Access',
    sector: 'POWER_GRID',
    country: 'South Africa',
    state: 'Eastern Cape',
    district: 'OR Tambo',
    sanctionedBudgetInCr: 18.0,
    spentBudgetInCr: 5.0,
    targetBeneficiaries: 75000,
    status: 'IN_PROGRESS',
    startDate: '2024-11-01',
    expectedCompletionDate: '2026-05-31',
    description: 'Dedicated clinic feeder and backup solar-battery units.',
    implementingAgency: 'Eskom Eastern Cape',
  },
];

export const INITIAL_GRIEVANCES: Grievance[] = [
  // Bahraich - Heavy Water Supply Crisis (Hotspot)
  {
    id: 'grv_001',
    ticketNumber: 'NXA-2026-8401',
    citizenPhone: '+919838120491',
    citizenName: 'Rameshwar Yadav',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Mere gaon Pipraich mein 3 hafte se paani nahi aa raha hai. Gaon ka primary handpump 1 mahine se kharab hai. Lagbhag 400 parivar paani ke liye 2 kilometer door talab par ja rahe hain.',
    translatedText: 'Water supply has stopped in my village Pipraich for 3 weeks. The main village handpump is broken for a month. Around 400 families are walking 2km to a pond.',
    category: 'WATER_SUPPLY',
    subCategory: 'Handpump Breakdown & Dry Borewell',
    description: 'Pipraich village community handpump broken, severe drinking water shortage affecting 400 households.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Bahraich',
      block: 'Phakharpur',
      villageWard: 'Pipraich',
      coordinates: { lat: 27.5612, lng: 81.6021 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 1600,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 94,
    confidenceScore: 0.98,
    verified: true,
    assignedDepartment: 'UP Jal Nigam (Rural)',
    createdAt: '2026-03-24T10:15:00Z',
    updatedAt: '2026-03-25T08:30:00Z',
  },
  {
    id: 'grv_002',
    ticketNumber: 'NXA-2026-8402',
    citizenPhone: '+919450338192',
    citizenName: 'Shanti Devi',
    channel: 'VOICE_CALL',
    language: 'hi',
    rawTranscript: 'Hamare gaon Majhara mein pipe line to dali gayi thi par paani ek boond bhi nahi aata. Sabhi nal sukhe pade hain. Bachhe bimar pad rahe hain ganda paani peene se.',
    translatedText: 'In our village Majhara pipes were laid but not a drop of water flows. All taps are dry. Children falling sick from drinking impure pond water.',
    category: 'WATER_SUPPLY',
    subCategory: 'Dry Tap Network / Non-functional Pipeline',
    description: 'Jal Jeevan Mission pipes laid but zero water pressure; pipeline damaged at junction.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Bahraich',
      block: 'Mahsi',
      villageWard: 'Majhara Tok',
      coordinates: { lat: 27.5230, lng: 81.4890 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 2200,
    status: 'REGISTERED',
    urgencyScore: 92,
    confidenceScore: 0.96,
    verified: true,
    assignedDepartment: 'UP Jal Nigam (Rural)',
    createdAt: '2026-03-24T14:42:00Z',
    updatedAt: '2026-03-24T14:42:00Z',
  },
  {
    id: 'grv_003',
    ticketNumber: 'NXA-2026-8403',
    citizenPhone: '+919120448110',
    citizenName: 'Mohd. Imran',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Kaisarganj ward number 4 me subah sirf 10 minute peele rang ka badbudar paani aata hai. Tanki ki cleaning 2 saal se nahi hui hai.',
    translatedText: 'In Kaisarganj ward 4, only 10 mins of yellow foul-smelling water comes in morning. Water tank has not been cleaned for 2 years.',
    category: 'WATER_SUPPLY',
    subCategory: 'Contaminated / Yellow Tap Water',
    description: 'Foul-smelling contaminated water in municipal line, high risk of water-borne epidemic.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Bahraich',
      block: 'Kaisarganj',
      villageWard: 'Ward 4 Old Market',
      coordinates: { lat: 27.2510, lng: 81.5430 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 850,
    status: 'UNDER_VERIFICATION',
    urgencyScore: 86,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'Nagar Panchayat Water Works',
    createdAt: '2026-03-25T09:12:00Z',
    updatedAt: '2026-03-25T09:12:00Z',
  },
  {
    id: 'grv_004',
    ticketNumber: 'NXA-2026-8404',
    citizenPhone: '+919935198274',
    citizenName: 'Baldev Prasad',
    channel: 'VOICE_CALL',
    language: 'hi',
    rawTranscript: 'Bhariya gaon me 4 tube-well motor jal gaya hai pichle 15 din se bijli voltage fluctuation ke karan. Khet sookh rahe hain aur peene ka paani bhi band hai.',
    translatedText: 'In Bhariya village 4 tube-well motors burnt due to power fluctuations 15 days ago. Fields drying up and drinking water stopped.',
    category: 'WATER_SUPPLY',
    subCategory: 'Tube-well Pump Failure',
    description: 'Submersible pump motor burn out leaving whole agricultural hamlet without drinking and irrigation water.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Bahraich',
      block: 'Jarwal',
      villageWard: 'Bhariya Kalan',
      coordinates: { lat: 27.1680, lng: 81.5620 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 1400,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 91,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'UP Jal Nigam & Discom',
    createdAt: '2026-03-25T11:20:00Z',
    updatedAt: '2026-03-25T13:00:00Z',
  },
  {
    id: 'grv_005',
    ticketNumber: 'NXA-2026-8405',
    citizenPhone: '+919871092837',
    citizenName: 'Gulab Singh',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Mihinpurwa forest border area me 3 mahine se pipeline leak hai, raste par paani beh raha hai aur gharon tak nahi pahunch raha.',
    translatedText: 'Mihinpurwa border village pipeline leaking for 3 months, water wasting on roads and not reaching houses.',
    category: 'WATER_SUPPLY',
    subCategory: 'Main Feeder Pipeline Rupture',
    description: 'Main feeder pipeline burst wasting treated water and flooding road.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Bahraich',
      block: 'Mihinpurwa',
      villageWard: 'Motipur',
      coordinates: { lat: 27.9120, lng: 81.3320 },
    },
    severity: 'MEDIUM',
    affectedPopulationEst: 600,
    status: 'IN_PROGRESS',
    urgencyScore: 68,
    confidenceScore: 0.92,
    verified: true,
    assignedDepartment: 'UP Jal Nigam',
    createdAt: '2026-03-23T16:40:00Z',
    updatedAt: '2026-03-24T10:00:00Z',
  },

  // Bahraich - Rural Roads & Healthcare
  {
    id: 'grv_006',
    ticketNumber: 'NXA-2026-8406',
    citizenPhone: '+919415287319',
    citizenName: 'Santosh Kumar Verma',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Mahsi se Chahlari ghat wala rasta pichli baadh me poora beh gaya tha. Aaj tak mitti tak nahi dali gayi. Ambulance gaon me nahi aa sakti.',
    translatedText: 'Road from Mahsi to Chahlari ghat washed away in last flood. Not even mud filling done. Ambulances cannot enter village.',
    category: 'RURAL_ROADS',
    subCategory: 'Washed Out Flood Embankment Road',
    description: 'Key access road washed away, 6 villages disconnected from CHC emergency health center.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Bahraich',
      block: 'Mahsi',
      villageWard: 'Chahlari',
      coordinates: { lat: 27.4890, lng: 81.3890 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 7500,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 96,
    confidenceScore: 0.97,
    verified: true,
    assignedDepartment: 'PWD Rural Roads',
    createdAt: '2026-03-25T15:10:00Z',
    updatedAt: '2026-03-26T09:00:00Z',
  },
  {
    id: 'grv_007',
    ticketNumber: 'NXA-2026-8407',
    citizenPhone: '+919792019482',
    citizenName: 'Dr. Anita Shukla',
    channel: 'WEB_PORTAL',
    language: 'en',
    rawTranscript: 'Primary Health Center at Chahlari lacks solar battery backup and cold chain for vaccines. Power cuts last 18 hours daily.',
    translatedText: 'Primary Health Center at Chahlari lacks solar battery backup and cold chain for vaccines. Power cuts last 18 hours daily.',
    category: 'HEALTHCARE',
    subCategory: 'PHC Vaccine Cold Chain Failure',
    description: 'No uninterrupted power for vital anti-venom and infant immunization storage.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Bahraich',
      block: 'Mahsi',
      villageWard: 'Chahlari PHC',
      coordinates: { lat: 27.4880, lng: 81.3910 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 12000,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 95,
    confidenceScore: 0.99,
    verified: true,
    assignedDepartment: 'Chief Medical Officer (CMO)',
    createdAt: '2026-03-24T08:00:00Z',
    updatedAt: '2026-03-24T11:00:00Z',
  },

  // Balrampur & Shravasti - High Vulnerability Gap
  {
    id: 'grv_008',
    ticketNumber: 'NXA-2026-8408',
    citizenPhone: '+919628391028',
    citizenName: 'Brijesh Pandey',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Tulsipur block me bijli ka transformer 2 hafte pehle jal gaya tha. 5 gaon me andhera chhaya hua hai. Board exam wale bachhe pareshan hain.',
    translatedText: 'Transformer in Tulsipur burnt 2 weeks ago. 5 villages in total darkness. Students preparing for exams suffering.',
    category: 'POWER_GRID',
    subCategory: 'Burnt 100kVA Transformer',
    description: 'Burnt distribution transformer leaving 5 habitations without electricity for 14 days.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Balrampur',
      block: 'Tulsipur',
      villageWard: 'Laxmanpur',
      coordinates: { lat: 27.5500, lng: 82.4100 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 3100,
    status: 'REGISTERED',
    urgencyScore: 87,
    confidenceScore: 0.96,
    verified: true,
    assignedDepartment: 'Madhyanchal Vidyut Vitaran Nigam',
    createdAt: '2026-03-25T17:30:00Z',
    updatedAt: '2026-03-25T17:30:00Z',
  },
  {
    id: 'grv_009',
    ticketNumber: 'NXA-2026-8409',
    citizenPhone: '+919451928374',
    citizenName: 'Ghanshyam Tiwari',
    channel: 'VOICE_CALL',
    language: 'hi',
    rawTranscript: 'Ikauna Shravasti me barish ka nala band hai aur ganda paani road par bhara hua hai. Dukanon ke andar paani ghus raha hai.',
    translatedText: 'In Ikauna Shravasti, storm drain is blocked and dirty sewage is overflowing onto main road and shops.',
    category: 'SANITATION',
    subCategory: 'Open Sewer Clogging & Urban Spill',
    description: 'Blocked masonry canal overflowing with black toxic waste onto the market corridor.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Shravasti',
      block: 'Ikauna',
      villageWard: 'Main Bazar',
      coordinates: { lat: 27.5300, lng: 81.9600 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 1800,
    status: 'UNDER_VERIFICATION',
    urgencyScore: 80,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'Nagar Panchayat Sanitation Wing',
    createdAt: '2026-03-26T07:15:00Z',
    updatedAt: '2026-03-26T07:15:00Z',
  },

  // Bihar - Gaya & Muzaffarpur (Groundwater arsenic / road cutoff)
  {
    id: 'grv_010',
    ticketNumber: 'NXA-2026-8410',
    citizenPhone: '+919934018274',
    citizenName: 'Upendra Paswan',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Wazirganj block Gaya mein paani me peela pan aur fluoride ki matra bahut jyada hai. Daant aur haddi ki bimari badh rahi hai. Filter plant lagwaya jaye.',
    translatedText: 'In Wazirganj block Gaya, water has heavy fluoride contamination. Bone and dental fluorosis spreading. Demand community filter plant.',
    category: 'WATER_SUPPLY',
    subCategory: 'Severe Fluoride & Heavy Metal Contamination',
    description: 'Groundwater high fluoride level causing widespread fluorosis; urgent requirement of Har Ghar Nal filtration booster.',
    location: {
      country: 'India',
      state: 'Bihar',
      district: 'Gaya',
      block: 'Wazirganj',
      villageWard: 'Taradih',
      coordinates: { lat: 24.8100, lng: 85.2200 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 4200,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 97,
    confidenceScore: 0.98,
    verified: true,
    assignedDepartment: 'Bihar PHED Water Quality Mission',
    createdAt: '2026-03-23T11:00:00Z',
    updatedAt: '2026-03-24T14:20:00Z',
  },
  {
    id: 'grv_011',
    ticketNumber: 'NXA-2026-8411',
    citizenPhone: '+919835019284',
    citizenName: 'Md. Shahid',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Minapur Muzaffarpur mein Budhi Gandak nadi ka bandh toota hua hai. Puliya gir chuka hai. 3 saal se koi project pass nahi hua.',
    translatedText: 'In Minapur Muzaffarpur, Budhi Gandak embankment culvert is collapsed for 3 years. No project sanctioned yet.',
    category: 'RURAL_ROADS',
    subCategory: 'Collapsed River Causeway / No Project Sanctioned',
    description: 'Crucial arterial bridge collapsed, completely isolating 18,000 villagers with zero sanctioned state scheme.',
    location: {
      country: 'India',
      state: 'Bihar',
      district: 'Muzaffarpur',
      block: 'Minapur',
      villageWard: 'Tengrari',
      coordinates: { lat: 26.2400, lng: 85.3900 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 18000,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 98,
    confidenceScore: 0.99,
    verified: true,
    assignedDepartment: 'Rural Works Department Bihar',
    createdAt: '2026-03-22T09:40:00Z',
    updatedAt: '2026-03-24T16:00:00Z',
  },

  // Maharashtra - Gadchiroli tribal healthcare & bridge access
  {
    id: 'grv_012',
    ticketNumber: 'NXA-2026-8412',
    citizenPhone: '+919422109283',
    citizenName: 'Devrao Madavi',
    channel: 'VOICE_CALL',
    language: 'mr',
    rawTranscript: 'आमच्या भामरागड तालुक्यात प्राथमिक आरोग्य केंद्रात डॉक्टर ६ महिन्यांपासून नाही. गरोदर महिलांना ५० किमी दूर गडचिरोलीला नेण्यासाठी रस्ताही नाही.',
    translatedText: 'No doctor in Bhamragad PHC for 6 months. No motorable road to transport pregnant women 50km to district hospital.',
    category: 'HEALTHCARE',
    subCategory: 'Unstaffed Remote Tribal PHC',
    description: 'Tribal community health post vacant without emergency obstetric or snakebite treatment staff.',
    location: {
      country: 'India',
      state: 'Maharashtra',
      district: 'Gadchiroli',
      block: 'Bhamragad',
      villageWard: 'Laheri',
      coordinates: { lat: 19.3400, lng: 80.3800 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 6400,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 99,
    confidenceScore: 0.98,
    verified: true,
    assignedDepartment: 'Maharashtra Tribal Health Mission',
    createdAt: '2026-03-24T18:00:00Z',
    updatedAt: '2026-03-25T10:30:00Z',
  },

  // Tamil Nadu & Assam Grievances
  {
    id: 'grv_013',
    ticketNumber: 'NXA-2026-8413',
    citizenPhone: '+919443019284',
    citizenName: 'Murugan Selvam',
    channel: 'WHATSAPP',
    language: 'ta',
    rawTranscript: 'பென்னாகரம் தாலுகாவில் உள்ள கிராமங்களில் குடிநீர் விநியோகம் 10 நாட்களாக முற்றிலும் நின்றுவிட்டது. போர்வெல் பம்ப் பழுதாகியுள்ளது.',
    translatedText: 'Drinking water supply in Pennagaram taluk villages completely stopped for 10 days due to high capacity borewell motor burnout.',
    category: 'WATER_SUPPLY',
    subCategory: 'Submersible Pump Burnout',
    description: 'Borewell pumping machinery burnt out leaving 3 hamlet streets in severe summer drought.',
    location: {
      country: 'India',
      state: 'Tamil Nadu',
      district: 'Dharmapuri',
      block: 'Pennagaram',
      villageWard: 'Eriyur',
      coordinates: { lat: 12.1100, lng: 77.9200 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 2100,
    status: 'IN_PROGRESS',
    urgencyScore: 84,
    confidenceScore: 0.97,
    verified: true,
    assignedDepartment: 'TWAD Board Tamil Nadu',
    createdAt: '2026-03-25T08:10:00Z',
    updatedAt: '2026-03-25T12:00:00Z',
  },
  {
    id: 'grv_014',
    ticketNumber: 'NXA-2026-8414',
    citizenPhone: '+919864019283',
    citizenName: 'Bikash Saikia',
    channel: 'WHATSAPP',
    language: 'as',
    rawTranscript: 'Sonitpur Dhekiajuli tea estate rasta barishot poora bahi gol. Tea garden workers sakal cycle ba gari chalabo nuware.',
    translatedText: 'Tea estate access road in Dhekiajuli washed out. Workers cannot commute or transport produce.',
    category: 'RURAL_ROADS',
    subCategory: 'Culvert Collapse in Tea Plantation Sector',
    description: 'Key rural connecting culvert broken under monsoon deluge.',
    location: {
      country: 'India',
      state: 'Assam',
      district: 'Sonitpur',
      block: 'Dhekiajuli',
      villageWard: 'Batachor',
      coordinates: { lat: 26.7000, lng: 92.5100 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 3500,
    status: 'UNDER_VERIFICATION',
    urgencyScore: 81,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'Assam PWD (Roads)',
    createdAt: '2026-03-25T14:30:00Z',
    updatedAt: '2026-03-25T14:30:00Z',
  },

  // BRICS Country Grievances
  {
    id: 'grv_015',
    ticketNumber: 'NXA-2026-8415',
    citizenPhone: '+27821094821',
    citizenName: 'Thabo Ndlovu',
    channel: 'WHATSAPP',
    language: 'en',
    rawTranscript: 'In Vhembe Limpopo, water tankers have not arrived for 4 weeks. Community boreholes are depleted and solar pumps vandalized.',
    translatedText: 'In Vhembe Limpopo, water tankers have not arrived for 4 weeks. Community boreholes are depleted and solar pumps vandalized.',
    category: 'WATER_SUPPLY',
    subCategory: 'Borehole Depletion & Tanker Failure',
    description: 'Prolonged drought and municipal tanker delivery stoppage affecting 5 rural villages.',
    location: {
      country: 'South Africa',
      state: 'Limpopo',
      district: 'Vhembe',
      block: 'Thulamela',
      villageWard: 'Malamulele',
      coordinates: { lat: -22.9800, lng: 30.6900 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 5800,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 93,
    confidenceScore: 0.96,
    verified: true,
    assignedDepartment: 'Department of Water and Sanitation (DWS)',
    createdAt: '2026-03-24T12:00:00Z',
    updatedAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'grv_016',
    ticketNumber: 'NXA-2026-8416',
    citizenPhone: '+559799182740',
    citizenName: 'Maria Silva',
    channel: 'WHATSAPP',
    language: 'pt',
    rawTranscript: 'Comunidade ribeirinha de Benjamin Constant sem energia solar há 20 dias após pane nas baterias comunitárias.',
    translatedText: 'Riverine community in Benjamin Constant without solar electricity for 20 days following battery bank failure.',
    category: 'POWER_GRID',
    subCategory: 'Isolated Riverine Solar Microgrid Failure',
    description: 'Off-grid solar storage failure shutting down refrigeration for fish catch and medical depot.',
    location: {
      country: 'Brazil',
      state: 'Amazonas',
      district: 'Alto Solimões',
      block: 'Benjamin Constant',
      villageWard: 'Comunidade Santo Antonio',
      coordinates: { lat: -4.3800, lng: -70.0300 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 1100,
    status: 'REGISTERED',
    urgencyScore: 85,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'Amazonas Energy Secretariat',
    createdAt: '2026-03-25T16:00:00Z',
    updatedAt: '2026-03-25T16:00:00Z',
  },
  // ---- Extra India coverage ----
  {
    id: 'grv_017',
    ticketNumber: 'NXA-2026-8417',
    citizenPhone: '+919829011223',
    citizenName: 'Kanhaiya Lal Sharma',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Jaipur ke Sanganer ward me 2 hafte se paani ka pressure bahut kam hai. Tanker time par nahi aa raha.',
    translatedText: 'Low water pressure in Sanganer Jaipur for 2 weeks. Tankers irregular.',
    category: 'WATER_SUPPLY',
    subCategory: 'Low Pressure Urban Supply',
    description: 'Intermittent low-pressure supply in Sanganer industrial belt affecting 900 households.',
    location: {
      country: 'India',
      state: 'Rajasthan',
      district: 'Jaipur',
      block: 'Sanganer',
      villageWard: 'Ward 32',
      coordinates: { lat: 26.91, lng: 75.79 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 3800,
    status: 'REGISTERED',
    urgencyScore: 82,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'PHED Rajasthan',
    createdAt: '2026-03-24T10:00:00Z',
    updatedAt: '2026-03-24T10:00:00Z',
  },
  {
    id: 'grv_018',
    ticketNumber: 'NXA-2026-8418',
    citizenPhone: '+919824055667',
    citizenName: 'Jignesh Patel',
    channel: 'WHATSAPP',
    language: 'gu',
    rawTranscript: 'Ahmedabad Naroda gam ma drainage overflow thai che, varsaad vagar pan rasta par gandu paani.',
    translatedText: 'Drainage overflow in Naroda Ahmedabad even without rain.',
    category: 'SANITATION',
    subCategory: 'Sewer Overflow',
    description: 'Choked trunk sewer overflowing onto Naroda main road.',
    location: {
      country: 'India',
      state: 'Gujarat',
      district: 'Ahmedabad',
      block: 'Naroda',
      villageWard: 'Naroda Gam',
      coordinates: { lat: 23.05, lng: 72.6 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 2600,
    status: 'UNDER_VERIFICATION',
    urgencyScore: 80,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'AMC Sanitation Dept',
    createdAt: '2026-03-24T12:00:00Z',
    updatedAt: '2026-03-24T12:00:00Z',
  },
  {
    id: 'grv_019',
    ticketNumber: 'NXA-2026-8419',
    citizenPhone: '+919845011122',
    citizenName: 'Ravi Kumar',
    channel: 'WHATSAPP',
    language: 'en',
    rawTranscript: 'Bellandur lake road near Bengaluru is flooded after every rain, school buses cannot pass.',
    translatedText: 'Bellandur lake road near Bengaluru is flooded after every rain, school buses cannot pass.',
    category: 'FLOOD_DRAINAGE',
    subCategory: 'Urban Waterlogging',
    description: 'Storm drain encroachment causing repeated waterlogging on school route.',
    location: {
      country: 'India',
      state: 'Karnataka',
      district: 'Bengaluru Urban',
      block: 'Mahadevapura',
      villageWard: 'Bellandur',
      coordinates: { lat: 12.93, lng: 77.68 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 5000,
    status: 'REGISTERED',
    urgencyScore: 83,
    confidenceScore: 0.96,
    verified: true,
    assignedDepartment: 'BBMP Stormwater Dept',
    createdAt: '2026-03-25T09:00:00Z',
    updatedAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'grv_020',
    ticketNumber: 'NXA-2026-8420',
    citizenPhone: '+919846033344',
    citizenName: 'Anitha Nair',
    channel: 'VOICE_CALL',
    language: 'ml',
    rawTranscript: 'Wayanad Kalpetta adivasi colonyil kudivellam illa, borewell vazhinju 10 divasamayi.',
    translatedText: 'No drinking water in Kalpetta tribal colony Wayanad for 10 days, borewell dried.',
    category: 'WATER_SUPPLY',
    subCategory: 'Borewell Drying',
    description: 'Summer source depletion in tribal hamlet.',
    location: {
      country: 'India',
      state: 'Kerala',
      district: 'Wayanad',
      block: 'Kalpetta',
      villageWard: 'Munderi Colony',
      coordinates: { lat: 11.61, lng: 76.08 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 1200,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 90,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'Kerala Water Authority',
    createdAt: '2026-03-23T08:00:00Z',
    updatedAt: '2026-03-24T09:00:00Z',
  },
  {
    id: 'grv_021',
    ticketNumber: 'NXA-2026-8421',
    citizenPhone: '+919876544332',
    citizenName: 'Harpreet Singh',
    channel: 'WHATSAPP',
    language: 'pa',
    rawTranscript: 'Ludhiana Samrala road te street lights band ne, raat nu hadse ho rahe ne.',
    translatedText: 'Street lights off on Samrala road Ludhiana, night accidents rising.',
    category: 'POWER_GRID',
    subCategory: 'Streetlight Feeder Failure',
    description: 'Feeder fault leaving 6km highway stretch dark.',
    location: {
      country: 'India',
      state: 'Punjab',
      district: 'Ludhiana',
      block: 'Samrala',
      villageWard: 'Neelon',
      coordinates: { lat: 30.85, lng: 76.19 },
    },
    severity: 'MEDIUM',
    affectedPopulationEst: 4000,
    status: 'REGISTERED',
    urgencyScore: 65,
    confidenceScore: 0.93,
    verified: true,
    assignedDepartment: 'PSPCL',
    createdAt: '2026-03-25T18:00:00Z',
    updatedAt: '2026-03-25T18:00:00Z',
  },
  {
    id: 'grv_022',
    ticketNumber: 'NXA-2026-8422',
    citizenPhone: '+919830011224',
    citizenName: 'Abdul Rahim',
    channel: 'WHATSAPP',
    language: 'bn',
    rawTranscript: 'Murshidabad Domkal block e primary school e teacher nei 3 mas dhore.',
    translatedText: 'No teacher in Domkal primary school Murshidabad for 3 months.',
    category: 'EDUCATION',
    subCategory: 'Teacher Vacancy',
    description: 'Single-teacher school vacant affecting 180 students.',
    location: {
      country: 'India',
      state: 'West Bengal',
      district: 'Murshidabad',
      block: 'Domkal',
      villageWard: 'Garaimari',
      coordinates: { lat: 24.13, lng: 88.53 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 900,
    status: 'UNDER_VERIFICATION',
    urgencyScore: 78,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'WB School Education Dept',
    createdAt: '2026-03-24T15:00:00Z',
    updatedAt: '2026-03-24T15:00:00Z',
  },
  {
    id: 'grv_023',
    ticketNumber: 'NXA-2026-8423',
    citizenPhone: '+919937766554',
    citizenName: 'Sukanta Majhi',
    channel: 'WHATSAPP',
    language: 'en',
    rawTranscript: 'Kalahandi Bhawanipatna PHC has no doctor at night, patients referred 60km.',
    translatedText: 'Kalahandi Bhawanipatna PHC has no doctor at night, patients referred 60km.',
    category: 'HEALTHCARE',
    subCategory: 'Night Staff Absence',
    description: 'No night medical officer in block PHC.',
    location: {
      country: 'India',
      state: 'Odisha',
      district: 'Kalahandi',
      block: 'Bhawanipatna',
      villageWard: 'PHC Campus',
      coordinates: { lat: 20.0, lng: 83.17 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 8000,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 92,
    confidenceScore: 0.96,
    verified: true,
    assignedDepartment: 'Odisha Health Dept',
    createdAt: '2026-03-23T19:00:00Z',
    updatedAt: '2026-03-24T10:00:00Z',
  },
  {
    id: 'grv_024',
    ticketNumber: 'NXA-2026-8424',
    citizenPhone: '+919455001122',
    citizenName: 'Pooja Verma',
    channel: 'WHATSAPP',
    language: 'hi',
    rawTranscript: 'Lucknow Chinhat me road par 1 mahine se streetlight kharab, transformer se spark nikal raha.',
    translatedText: 'Streetlight faulty for a month in Chinhat Lucknow, transformer sparking.',
    category: 'POWER_GRID',
    subCategory: 'Unsafe Transformer',
    description: 'Sparking distribution transformer in residential lane.',
    location: {
      country: 'India',
      state: 'Uttar Pradesh',
      district: 'Lucknow',
      block: 'Chinhat',
      villageWard: 'Matiyari',
      coordinates: { lat: 26.89, lng: 81.05 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 1500,
    status: 'IN_PROGRESS',
    urgencyScore: 84,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'LES A Lucknow',
    createdAt: '2026-03-25T11:00:00Z',
    updatedAt: '2026-03-25T14:00:00Z',
  },
  // ---- Egypt / Ethiopia ----
  {
    id: 'grv_025',
    ticketNumber: 'NXA-2026-8425',
    citizenPhone: '+201011223344',
    citizenName: 'Ahmed Hassan',
    channel: 'WHATSAPP',
    language: 'ar',
    rawTranscript: 'Giza Faisal district water cut daily 8 hours, old asbestos pipes leaking.',
    translatedText: 'Daily 8-hour water cuts in Faisal Giza, old pipes leaking.',
    category: 'WATER_SUPPLY',
    subCategory: 'Network Leakage',
    description: 'Aged distribution network with 40% leakage in dense urban block.',
    location: {
      country: 'Egypt',
      state: 'Giza',
      district: 'Giza',
      block: 'Faisal',
      villageWard: 'El Mariouteya',
      coordinates: { lat: 30.01, lng: 31.19 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 6000,
    status: 'REGISTERED',
    urgencyScore: 82,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'Giza Water Company',
    createdAt: '2026-03-24T10:00:00Z',
    updatedAt: '2026-03-24T10:00:00Z',
  },
  {
    id: 'grv_026',
    ticketNumber: 'NXA-2026-8426',
    citizenPhone: '+201055667788',
    citizenName: 'Mona Ibrahim',
    channel: 'WHATSAPP',
    language: 'ar',
    rawTranscript: 'Aswan Kom Ombo village road washed out, school children crossing drain.',
    translatedText: 'Village access road washed out in Kom Ombo Aswan.',
    category: 'RURAL_ROADS',
    subCategory: 'Flood Damage',
    description: 'Unpaved access road eroded, 3 villages cut off.',
    location: {
      country: 'Egypt',
      state: 'Aswan',
      district: 'Aswan',
      block: 'Kom Ombo',
      villageWard: 'El Shطب',
      coordinates: { lat: 24.47, lng: 32.94 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 4500,
    status: 'REGISTERED',
    urgencyScore: 81,
    confidenceScore: 0.93,
    verified: true,
    assignedDepartment: 'Aswan Roads Authority',
    createdAt: '2026-03-25T08:00:00Z',
    updatedAt: '2026-03-25T08:00:00Z',
  },
  {
    id: 'grv_027',
    ticketNumber: 'NXA-2026-8427',
    citizenPhone: '+251911223344',
    citizenName: 'Abebe Tesfaye',
    channel: 'WHATSAPP',
    language: 'am',
    rawTranscript: 'Addis Ababa Akaki school has no toilets, 400 students sharing two rooms.',
    translatedText: 'Akaki school Addis Ababa has no functional toilets.',
    category: 'SANITATION',
    subCategory: 'School WASH',
    description: 'School sanitation block collapsed.',
    location: {
      country: 'Ethiopia',
      state: 'Addis Ababa',
      district: 'Addis Ababa',
      block: 'Akaki Kality',
      villageWard: 'Woreda 8',
      coordinates: { lat: 8.89, lng: 38.78 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 2000,
    status: 'UNDER_VERIFICATION',
    urgencyScore: 79,
    confidenceScore: 0.93,
    verified: true,
    assignedDepartment: 'Addis Education Bureau',
    createdAt: '2026-03-24T09:00:00Z',
    updatedAt: '2026-03-24T09:00:00Z',
  },
  {
    id: 'grv_028',
    ticketNumber: 'NXA-2026-8428',
    citizenPhone: '+251922334455',
    citizenName: 'Mulugeta Alemu',
    channel: 'WHATSAPP',
    language: 'am',
    rawTranscript: 'Gondar Dembia health post no malaria drugs for a month.',
    translatedText: 'No malaria drugs in Dembia health post Gondar for a month.',
    category: 'HEALTHCARE',
    subCategory: 'Drug Stockout',
    description: 'Essential drug stockout during peak season.',
    location: {
      country: 'Ethiopia',
      state: 'Amhara',
      district: 'Gondar',
      block: 'Dembia',
      villageWard: 'Kolladiba',
      coordinates: { lat: 12.42, lng: 37.12 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 9000,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 93,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'Amhara Health Bureau',
    createdAt: '2026-03-23T07:00:00Z',
    updatedAt: '2026-03-24T08:00:00Z',
  },
  // ---- Iran / Saudi / UAE / Indonesia ----
  {
    id: 'grv_029',
    ticketNumber: 'NXA-2026-8429',
    citizenPhone: '+989121112233',
    citizenName: 'Reza Ahmadi',
    channel: 'WHATSAPP',
    language: 'fa',
    rawTranscript: 'Tehran Eslamshahr water pressure very low on upper floors for 3 weeks.',
    translatedText: 'Low water pressure on upper floors in Eslamshahr Tehran.',
    category: 'WATER_SUPPLY',
    subCategory: 'Pressure Deficit',
    description: 'High-rise blocks without booster supply.',
    location: {
      country: 'Iran',
      state: 'Tehran',
      district: 'Tehran',
      block: 'Eslamshahr',
      villageWard: 'Zone 4',
      coordinates: { lat: 35.56, lng: 51.24 },
    },
    severity: 'MEDIUM',
    affectedPopulationEst: 7000,
    status: 'REGISTERED',
    urgencyScore: 68,
    confidenceScore: 0.92,
    verified: true,
    assignedDepartment: 'Tehran Water Authority',
    createdAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-03-25T10:00:00Z',
  },
  {
    id: 'grv_030',
    ticketNumber: 'NXA-2026-8430',
    citizenPhone: '+989133344455',
    citizenName: 'Fatemeh Karimi',
    channel: 'WHATSAPP',
    language: 'fa',
    rawTranscript: 'Ahvaz Padad area air pollution and dusty water from canal.',
    translatedText: 'Dusty canal water in Padad Ahvaz.',
    category: 'WATER_SUPPLY',
    subCategory: 'Canal Turbidity',
    description: 'Turbid canal supply after dust storms.',
    location: {
      country: 'Iran',
      state: 'Khuzestan',
      district: 'Ahvaz',
      block: 'Padad',
      villageWard: 'Kianpars',
      coordinates: { lat: 31.3, lng: 48.68 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 3500,
    status: 'REGISTERED',
    urgencyScore: 80,
    confidenceScore: 0.93,
    verified: true,
    assignedDepartment: 'Khuzestan Water Dept',
    createdAt: '2026-03-24T16:00:00Z',
    updatedAt: '2026-03-24T16:00:00Z',
  },
  {
    id: 'grv_031',
    ticketNumber: 'NXA-2026-8431',
    citizenPhone: '+966511223344',
    citizenName: 'Abdullah Alotaibi',
    channel: 'WHATSAPP',
    language: 'ar',
    rawTranscript: 'Riyadh Al Naseem power cuts daily during peak heat.',
    translatedText: 'Daily peak-hour power cuts in Al Naseem Riyadh.',
    category: 'POWER_GRID',
    subCategory: 'Feeder Overload',
    description: 'Overloaded feeder tripping in heatwave.',
    location: {
      country: 'Saudi Arabia',
      state: 'Riyadh',
      district: 'Riyadh',
      block: 'Al Naseem',
      villageWard: 'Eastern Ring',
      coordinates: { lat: 24.74, lng: 46.83 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 10000,
    status: 'IN_PROGRESS',
    urgencyScore: 83,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'Saudi Electricity Co.',
    createdAt: '2026-03-25T13:00:00Z',
    updatedAt: '2026-03-25T13:00:00Z',
  },
  {
    id: 'grv_032',
    ticketNumber: 'NXA-2026-8432',
    citizenPhone: '+966522334455',
    citizenName: 'Sara Aljohani',
    channel: 'WHATSAPP',
    language: 'ar',
    rawTranscript: 'Jeddah Al Harazat flooding after rain, sewage mixed.',
    translatedText: 'Flooding with sewage mix in Al Harazat Jeddah.',
    category: 'FLOOD_DRAINAGE',
    subCategory: 'Storm Sewer Mix',
    description: 'Undersized storm drains overflowing.',
    location: {
      country: 'Saudi Arabia',
      state: 'Makkah',
      district: 'Jeddah',
      block: 'Al Harazat',
      villageWard: 'Eastern Jeddah',
      coordinates: { lat: 21.55, lng: 39.25 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 5500,
    status: 'REGISTERED',
    urgencyScore: 84,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'Jeddah Municipality',
    createdAt: '2026-03-24T14:00:00Z',
    updatedAt: '2026-03-24T14:00:00Z',
  },
  {
    id: 'grv_033',
    ticketNumber: 'NXA-2026-8433',
    citizenPhone: '+971501122334',
    citizenName: 'Khalid Mansoor',
    channel: 'WHATSAPP',
    language: 'en',
    rawTranscript: 'Dubai Al Quoz labour camp AC failing, water salty.',
    translatedText: 'AC failure and salty water in Al Quoz camp Dubai.',
    category: 'WATER_SUPPLY',
    subCategory: 'Brackish Supply',
    description: 'Desalination top-up irregular in camp block.',
    location: {
      country: 'UAE',
      state: 'Dubai',
      district: 'Dubai',
      block: 'Al Quoz',
      villageWard: 'Camp 4',
      coordinates: { lat: 25.14, lng: 55.23 },
    },
    severity: 'MEDIUM',
    affectedPopulationEst: 1800,
    status: 'REGISTERED',
    urgencyScore: 66,
    confidenceScore: 0.92,
    verified: true,
    assignedDepartment: 'DEWA Community Services',
    createdAt: '2026-03-25T12:00:00Z',
    updatedAt: '2026-03-25T12:00:00Z',
  },
  {
    id: 'grv_034',
    ticketNumber: 'NXA-2026-8434',
    citizenPhone: '+971522334455',
    citizenName: 'Priya Nair',
    channel: 'WHATSAPP',
    language: 'en',
    rawTranscript: 'Mussafah Abu Dhabi internal roads broken, school bus delayed daily.',
    translatedText: 'Broken internal roads in Mussafah Abu Dhabi.',
    category: 'RURAL_ROADS',
    subCategory: 'Internal Road Damage',
    description: 'Industrial area roads potholed.',
    location: {
      country: 'UAE',
      state: 'Abu Dhabi',
      district: 'Abu Dhabi',
      block: 'Mussafah',
      villageWard: 'M-11',
      coordinates: { lat: 24.36, lng: 54.47 },
    },
    severity: 'MEDIUM',
    affectedPopulationEst: 3000,
    status: 'REGISTERED',
    urgencyScore: 62,
    confidenceScore: 0.91,
    verified: true,
    assignedDepartment: 'Abu Dhabi Municipality',
    createdAt: '2026-03-24T11:00:00Z',
    updatedAt: '2026-03-24T11:00:00Z',
  },
  {
    id: 'grv_035',
    ticketNumber: 'NXA-2026-8435',
    citizenPhone: '+6281211223344',
    citizenName: 'Budi Santoso',
    channel: 'WHATSAPP',
    language: 'id',
    rawTranscript: 'Jakarta Timur banjir setiap hujan, selokan mampet sampah.',
    translatedText: 'Flooding every rain in East Jakarta, drains clogged.',
    category: 'FLOOD_DRAINAGE',
    subCategory: 'Clogged Drains',
    description: 'Solid waste blocking secondary drains.',
    location: {
      country: 'Indonesia',
      state: 'Jakarta',
      district: 'East Jakarta',
      block: 'Cakung',
      villageWard: 'Rawa Terate',
      coordinates: { lat: -6.18, lng: 106.93 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 7500,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 86,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'DKI Water Agency',
    createdAt: '2026-03-24T07:00:00Z',
    updatedAt: '2026-03-25T08:00:00Z',
  },
  {
    id: 'grv_036',
    ticketNumber: 'NXA-2026-8436',
    citizenPhone: '+6281333445566',
    citizenName: 'Siti Rahayu',
    channel: 'WHATSAPP',
    language: 'id',
    rawTranscript: 'Surabaya Kenjeran puskesmas antre lama, dokter hanya satu.',
    translatedText: 'Long queues at Kenjeran health center Surabaya, only one doctor.',
    category: 'HEALTHCARE',
    subCategory: 'Staff Shortage',
    description: 'Understaffed coastal puskesmas.',
    location: {
      country: 'Indonesia',
      state: 'East Java',
      district: 'Surabaya',
      block: 'Kenjeran',
      villageWard: 'Bulak Banteng',
      coordinates: { lat: -7.22, lng: 112.78 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 6000,
    status: 'REGISTERED',
    urgencyScore: 81,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'Surabaya Health Office',
    createdAt: '2026-03-25T09:00:00Z',
    updatedAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'grv_037',
    ticketNumber: 'NXA-2026-8437',
    citizenPhone: '+27835566778',
    citizenName: 'Nomsa Dlamini',
    channel: 'WHATSAPP',
    language: 'en',
    rawTranscript: 'OR Tambo Lusikisiki clinic without power for 5 days, vaccines at risk.',
    translatedText: 'Clinic without power 5 days in Lusikisiki OR Tambo.',
    category: 'POWER_GRID',
    subCategory: 'Clinic Outage',
    description: 'Feeder fault threatening cold chain.',
    location: {
      country: 'South Africa',
      state: 'Eastern Cape',
      district: 'OR Tambo',
      block: 'Lusikisiki',
      villageWard: 'Hombe Clinic',
      coordinates: { lat: -31.36, lng: 29.57 },
    },
    severity: 'CRITICAL',
    affectedPopulationEst: 4800,
    status: 'ESCALATED_TO_PLANNING',
    urgencyScore: 91,
    confidenceScore: 0.95,
    verified: true,
    assignedDepartment: 'Eskom Eastern Cape',
    createdAt: '2026-03-24T08:00:00Z',
    updatedAt: '2026-03-25T09:00:00Z',
  },
  {
    id: 'grv_038',
    ticketNumber: 'NXA-2026-8438',
    citizenPhone: '+559399887766',
    citizenName: 'Joao Pereira',
    channel: 'WHATSAPP',
    language: 'pt',
    rawTranscript: 'Santarem Alter do Chao sem agua potavel ha 12 dias.',
    translatedText: 'No potable water in Alter do Chao Santarem for 12 days.',
    category: 'WATER_SUPPLY',
    subCategory: 'Treatment Outage',
    description: 'Small treatment plant pump failure.',
    location: {
      country: 'Brazil',
      state: 'Para',
      district: 'Santarem',
      block: 'Alter do Chao',
      villageWard: 'Vila Central',
      coordinates: { lat: -2.51, lng: -54.95 },
    },
    severity: 'HIGH',
    affectedPopulationEst: 2800,
    status: 'REGISTERED',
    urgencyScore: 82,
    confidenceScore: 0.94,
    verified: true,
    assignedDepartment: 'COSANPA Para',
    createdAt: '2026-03-25T10:00:00Z',
    updatedAt: '2026-03-25T10:00:00Z',
  },
];

export const INITIAL_PLAN_GAPS: PolicyGapInsight[] = [
  {
    id: 'gap_01',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Bahraich',
    sector: 'WATER_SUPPLY',
    citizenDemandScore: 94,
    activeProjectBudgetInCr: 68.5,
    activeProjectsCount: 1,
    totalComplaints: 48,
    criticalComplaints: 29,
    gapSeverity: 'CRITICAL_UNFUNDED',
    affectedPopulation: 380000,
    primaryKeyProblem: 'Phakharpur & Mahsi blocks lack deep aquifer drilling & automated pump replacements in JJM Phase 1.',
    aiRationale: 'Citizen grievance volume in Bahraich Water Supply surged by 185% over last 60 days. Current JJM Phase 1 scheme covers only 42 of 148 revenue villages, leaving ~380,000 citizens with seasonal dry wells and contamination.',
    recommendedAction: 'Sanction supplementary fast-track Jal Jeevan Mission Phase 2 grant of ₹85 Cr targeting 84 uncovered flood-prone riverine habitations in Mahsi and Kaisarganj.',
    estimatedBudgetRequiredInCr: 85.0,
  },
  {
    id: 'gap_02',
    country: 'India',
    state: 'Bihar',
    district: 'Gaya',
    sector: 'WATER_SUPPLY',
    citizenDemandScore: 91,
    activeProjectBudgetInCr: 88.0,
    activeProjectsCount: 1,
    totalComplaints: 36,
    criticalComplaints: 22,
    gapSeverity: 'CRITICAL_UNFUNDED',
    affectedPopulation: 290000,
    primaryKeyProblem: 'Severe fluoride and heavy mineral toxicity in Wazirganj and Fatehpur groundwater; existing budget lacks reverse osmosis community filters.',
    aiRationale: 'While piped lines exist, 64% of grievances report unpotable high-fluoride water causing chronic fluorosis. Current project allocation only funds distribution pipes, not treatment plants.',
    recommendedAction: 'Reallocate ₹32 Cr towards 45 community-level solar electrolytic defluoridation treatment units across Wazirganj and Mohanpur blocks.',
    estimatedBudgetRequiredInCr: 32.0,
  },
  {
    id: 'gap_03',
    country: 'India',
    state: 'Bihar',
    district: 'Muzaffarpur',
    sector: 'RURAL_ROADS',
    citizenDemandScore: 88,
    activeProjectBudgetInCr: 0.0,
    activeProjectsCount: 0,
    totalComplaints: 29,
    criticalComplaints: 18,
    gapSeverity: 'CRITICAL_UNFUNDED',
    affectedPopulation: 175000,
    primaryKeyProblem: 'Zero sanctioned bridge/culvert reconstruction projects for Budhi Gandak flood bypass in FY 2025-26 budget.',
    aiRationale: 'Total policy blindspot: 29 severe grievances logged regarding washed out river causeways isolating 18 villages. No corresponding scheme exists in current annual action plan.',
    recommendedAction: 'Immediately enlist Minapur-Tengrari road under PMGSY-IV Special Flood Mitigation Package with emergency allocation of ₹42 Cr.',
    estimatedBudgetRequiredInCr: 42.0,
  },
  {
    id: 'gap_04',
    country: 'India',
    state: 'Maharashtra',
    district: 'Gadchiroli',
    sector: 'HEALTHCARE',
    citizenDemandScore: 86,
    activeProjectBudgetInCr: 12.0,
    activeProjectsCount: 1,
    totalComplaints: 24,
    criticalComplaints: 16,
    gapSeverity: 'HIGH_DEFICIT',
    affectedPopulation: 140000,
    primaryKeyProblem: 'Severe shortage of doctors, 24x7 solar vaccine cold chains, and mobile emergency ambulance boats in Bhamragad & Sironcha.',
    aiRationale: 'Tribal mortality risk is elevated by lack of emergency medical transit during 4 months of monsoon isolation. Current state budget provides only basic OPD supplies.',
    recommendedAction: 'Deploy 4 All-Terrain Mobile Medical Units (MMUs) and sanction 100% solar microgrid retrofitting for all 18 primary health subcenters (₹18 Cr).',
    estimatedBudgetRequiredInCr: 18.0,
  },
  {
    id: 'gap_05',
    country: 'India',
    state: 'Uttar Pradesh',
    district: 'Balrampur',
    sector: 'POWER_GRID',
    citizenDemandScore: 82,
    activeProjectBudgetInCr: 15.0,
    activeProjectsCount: 1,
    totalComplaints: 21,
    criticalComplaints: 12,
    gapSeverity: 'HIGH_DEFICIT',
    affectedPopulation: 180000,
    primaryKeyProblem: 'Frequent 100kVA transformer burnouts and 33/11kV substation overload in Tulsipur & Gainsari blocks.',
    aiRationale: 'Discom replacement turnaround exceeds 14 days vs mandated 48 hours. Voltage drops damage tube wells and student study periods.',
    recommendedAction: 'Sanction RDSS feeder separation project and reserve inventory depot of 50 spare transformers in Balrampur HQ (₹25 Cr).',
    estimatedBudgetRequiredInCr: 25.0,
  },
  {
    id: 'gap_06',
    country: 'India',
    state: 'Odisha',
    district: 'Kalahandi',
    sector: 'HEALTHCARE',
    citizenDemandScore: 89,
    activeProjectBudgetInCr: 12.0,
    activeProjectsCount: 1,
    totalComplaints: 18,
    criticalComplaints: 11,
    gapSeverity: 'CRITICAL_UNFUNDED',
    affectedPopulation: 150000,
    primaryKeyProblem: 'No night medical officers and weak referral transport in Bhawanipatna block.',
    aiRationale: 'Night-time PHC vacancy forces 60km referrals; current package covers only day OPD.',
    recommendedAction: 'Sanction 24x7 PHC staffing plus 6 ambulances under NHM (₹16 Cr).',
    estimatedBudgetRequiredInCr: 16.0,
  },
  {
    id: 'gap_07',
    country: 'Egypt',
    state: 'Giza',
    district: 'Giza',
    sector: 'WATER_SUPPLY',
    citizenDemandScore: 84,
    activeProjectBudgetInCr: 20.0,
    activeProjectsCount: 1,
    totalComplaints: 16,
    criticalComplaints: 9,
    gapSeverity: 'HIGH_DEFICIT',
    affectedPopulation: 220000,
    primaryKeyProblem: 'Asbestos cement network leakage in Faisal; replacement covers only phase 1.',
    aiRationale: 'Leakage losses keep pressure low despite treatment availability.',
    recommendedAction: 'Extend pipe replacement to 90km across Faisal and Boulaq (₹38 Cr).',
    estimatedBudgetRequiredInCr: 38.0,
  },
  {
    id: 'gap_08',
    country: 'Ethiopia',
    state: 'Amhara',
    district: 'Gondar',
    sector: 'HEALTHCARE',
    citizenDemandScore: 90,
    activeProjectBudgetInCr: 8.0,
    activeProjectsCount: 1,
    totalComplaints: 14,
    criticalComplaints: 10,
    gapSeverity: 'CRITICAL_UNFUNDED',
    affectedPopulation: 200000,
    primaryKeyProblem: 'Essential drug stockouts and no solar cold chain in 22 health posts.',
    aiRationale: 'Peak-season malaria demand exceeds funded buffer stock.',
    recommendedAction: 'Fund revolving drug stock and solar fridges for all posts (₹14 Cr).',
    estimatedBudgetRequiredInCr: 14.0,
  },
  {
    id: 'gap_09',
    country: 'Indonesia',
    state: 'Jakarta',
    district: 'East Jakarta',
    sector: 'FLOOD_DRAINAGE',
    citizenDemandScore: 87,
    activeProjectBudgetInCr: 15.0,
    activeProjectsCount: 1,
    totalComplaints: 19,
    criticalComplaints: 10,
    gapSeverity: 'HIGH_DEFICIT',
    affectedPopulation: 260000,
    primaryKeyProblem: 'Clogged secondary drains in Cakung; dredging covers only main canal.',
    aiRationale: 'Waste-blocked secondaries cause repeat local flooding.',
    recommendedAction: 'Scale drain cleaning and waste traps to 12 kelurahan (₹20 Cr).',
    estimatedBudgetRequiredInCr: 20.0,
  },
  {
    id: 'gap_10',
    country: 'Brazil',
    state: 'Para',
    district: 'Santarem',
    sector: 'WATER_SUPPLY',
    citizenDemandScore: 83,
    activeProjectBudgetInCr: 6.0,
    activeProjectsCount: 1,
    totalComplaints: 12,
    criticalComplaints: 7,
    gapSeverity: 'HIGH_DEFICIT',
    affectedPopulation: 60000,
    primaryKeyProblem: 'Single treatment pump with no standby in Alter do Chao.',
    aiRationale: 'Any pump outage stops potable supply for 12+ days.',
    recommendedAction: 'Install standby pump plus intake protection (₹9 Cr).',
    estimatedBudgetRequiredInCr: 9.0,
  },
];
